import { test, expect } from './fixtures';
import { randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { mailLink } from '../../scripts/test-mail.mjs';

test('complete purchase-plan-CSV/OFX-payment-refund cycle while keeping actual payments and corrections', async ({ page }) => {
  test.setTimeout(120000); const origin='http://127.0.0.1:15173',email=`cycle-${randomUUID()}@rovere.test`,password='Fictitious-browser-123!';
  expect((await page.request.post('/api/auth/sign-up/email',{headers:{Origin:origin},data:{name:'Pessoa fictícia',email,password}})).status()).toBe(200); await page.goto(await mailLink(email,'Confirme')); await page.getByLabel('Email',{exact:true}).fill(email); await page.getByLabel('Senha',{exact:true}).fill(password); await page.getByRole('button',{name:'Entrar',exact:true}).click();
  await page.getByLabel('Nome da conta',{exact:true}).fill('Banco do ciclo'); await page.getByRole('button',{name:'Adicionar conta',exact:true}).click(); await page.getByLabel('Nome da conta de crédito').fill('Crédito do ciclo'); await page.getByRole('button',{name:'Adicionar conta de crédito',exact:true}).click(); for(const period of ['2026-10','2026-11']) {await page.getByLabel('Competência da fatura').fill(period);await page.getByRole('button',{name:'Confirmar competência',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Competência cadastrada e confirmada'})).toBeVisible();}
  await page.getByLabel('Descrição da compra',{exact:true}).fill('Compra do ciclo'); await page.getByLabel('Data original da compra',{exact:true}).fill('2026-09-01'); await page.getByLabel('Total da compra em reais',{exact:true}).fill('100,00'); await page.getByLabel('Notas da compra',{exact:true}).fill('Correção manual preservada'); await page.getByRole('button',{name:'Cadastrar compra',exact:true}).click(); await expect(page.getByTestId('expense-summary')).toContainText('Dados completos');
  await page.getByLabel('Quantidade de parcelas do plano',{exact:true}).fill('2');await page.getByRole('combobox',{name:'Crédito do plano',exact:true}).selectOption({label:'Crédito do ciclo'});await page.getByLabel('Primeira competência do plano',{exact:true}).fill('2026-10');await page.getByLabel('Confirmo o total da compra, a quantidade e o calendário mensal deste plano.').check();await page.getByRole('button',{name:'Confirmar plano de parcelas',exact:true}).click();await expect(page.getByTestId('installment-plan-summary')).toContainText('2 previsões pendentes');
  await page.getByText('Colunas opcionais',{exact:true}).click();await page.getByLabel('Identificador externo',{exact:true}).fill('ID');
  const csv='Data;Descrição;Valor;ID\n08/10/2026;Parcela CSV do ciclo;-50,00;cycle-csv';const template=await readFile('packages/importers/test/fixtures/card-220.ofx','utf8');const entry=template.match(/<STMTTRN>[\s\S]*?<\/STMTTRN>/)![0].replace(/<FITID>[^<]+<\/FITID>/,'<FITID>cycle-ofx</FITID>').replace(/<TRNAMT>[^<]+<\/TRNAMT>/,'<TRNAMT>-50.00</TRNAMT>').replace('Loja &amp; Café fictícios','Parcela OFX do ciclo');const ofx=template.replace(/<STMTTRN>[\s\S]*<\/STMTTRN>/,entry);
  async function upload(format:'csv'|'ofx',contents:string,kind:'bank'|'card',period?:string) {await page.getByRole('combobox',{name:'Formato do arquivo',exact:true}).selectOption(format);if(format==='csv'){await page.getByRole('combobox',{name:'Natureza do CSV',exact:true}).selectOption(kind);await page.getByLabel('Conferi o mapeamento, a moeda BRL e os formatos acima.').check();}await page.getByLabel('Arquivo para revisão').setInputFiles({name:`cycle.${format}`,mimeType:'application/octet-stream',buffer:Buffer.from(contents)});await page.getByRole('button',{name:'Enviar para revisão',exact:true}).click();await expect(page.getByTestId('import-status')).toContainText('Em revisão');if(kind==='card'){await page.getByRole('combobox',{name:'Crédito para este bloco',exact:true}).selectOption({label:'Crédito do ciclo'});await page.getByRole('combobox',{name:'Competência para este bloco',exact:true}).selectOption({label:period!});}else await page.getByRole('combobox',{name:'Conta para este bloco',exact:true}).selectOption({label:'Banco do ciclo'});await page.getByRole('button',{name:'Salvar destino do bloco 1',exact:true}).click();await expect(page.getByTestId('confirmation-preview')).toHaveText('1 novos · 0 vinculados · 0 ignorados');await page.getByRole('button',{name:'Confirmar registros selecionados',exact:true}).click();await expect(page.getByTestId('confirmation-result')).toHaveText('1 novos · 0 vinculados · 0 ignorados');}
  for(const [format,contents,period,number] of [['csv',csv,'2026-10','1'],['ofx',ofx,'2026-11','2']] as const) {await upload(format,contents,'card',period);await page.getByRole('combobox',{name:'Fatura para editar',exact:true}).selectOption({label:period});const button=page.getByRole('table',{name:'Natureza dos registros da fatura',exact:true}).getByRole('button',{name:/Classificar:/}).first();await button.click();await page.getByRole('combobox',{name:'Natureza confirmada da linha',exact:true}).selectOption('purchase');await page.getByLabel('Magnitude confirmada em reais',{exact:true}).fill('50,00');await page.getByLabel('Confirmo a natureza e o valor informados, preservando os dados originais.').check();await page.getByRole('button',{name:'Salvar natureza da linha',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Natureza salva'})).toBeVisible();await page.getByRole('combobox',{name:'Parcela prevista para conciliar',exact:true}).selectOption(number);const selector=page.getByRole('combobox',{name:'Cobrança para conciliar',exact:true});await expect(selector).toBeEnabled();await selector.selectOption({index:1});await page.getByLabel('Valor efetivo confirmado em reais',{exact:true}).fill('50,00');await page.getByLabel('Confirmo a parcela selecionada, o vínculo com esta compra e o valor efetivo informado.').check();await page.getByRole('button',{name:'Conciliar parcela com cobrança',exact:true}).click();await expect(page.getByTestId('installment-plan-summary')).toContainText(`${number} cobranças conciliadas`);}
  await upload('csv','Data;Descrição;Valor;ID\n08/11/2026;Pagamento do ciclo;-50,00;cycle-bank','bank');await page.getByRole('combobox',{name:'Fatura para editar',exact:true}).selectOption({label:'2026-10'});
  async function coverage(){await page.getByLabel('Conferi que todos os registros desta fatura estão presentes e têm natureza confirmada.').check();await page.getByRole('button',{name:'Confirmar cobertura completa dos registros atuais',exact:true}).click();await expect(page.getByTestId('statement-calculation-summary')).toContainText('Completa e atual');}
  async function basis(preserve=false){await page.getByRole('combobox',{name:'Base da obrigação para pagamento',exact:true}).selectOption('calculated');await page.getByLabel('Confirmo que esta base é o total da obrigação antes dos pagamentos, mesmo quando houver divergência.').check();await page.getByLabel('Confirmo que a base não repete obrigação já representada em outra fatura.').check();if(preserve)await page.getByLabel('Confirmo preservar pagamentos reais e deixar eventual excedente de crédito para revisão, sem liberar caixa.').check();await page.getByRole('button',{name:'Confirmar base para pagamentos',exact:true}).click();}
  await coverage();await basis();await expect(page.getByTestId('statement-payment-summary')).toContainText('Estado: Não pago');await page.getByRole('combobox',{name:'Conta bancária do pagamento',exact:true}).selectOption({label:'Banco do ciclo'});await page.getByRole('combobox',{name:'Movimento bancário para alocar',exact:true}).selectOption({label:'2026-11-08 · Pagamento do ciclo · BRL -50,00'});await page.getByLabel('Magnitude total da saída em reais',{exact:true}).fill('50,00');await page.getByLabel('Valor a alocar nesta fatura em reais',{exact:true}).fill('50,00');await page.getByLabel('Confirmo que este movimento é uma saída bancária e que os valores informados correspondem ao pagamento desta fatura.').check();await page.getByRole('button',{name:'Alocar pagamento bancário',exact:true}).click();await expect(page.getByTestId('statement-payment-summary')).toContainText('Estado: Pago pelas alocações');
  await page.getByLabel('Data do ajuste informado',{exact:true}).fill('2026-11-09');await page.getByLabel('Descrição do ajuste',{exact:true}).fill('Estorno parcial do ciclo');await page.getByLabel('Valor do ajuste com sinal',{exact:true}).fill('20,00');await page.getByRole('combobox',{name:'Natureza do ajuste',exact:true}).selectOption('refund');await page.getByLabel('Magnitude do ajuste em reais',{exact:true}).fill('20,00');await page.getByLabel('Motivo do ajuste',{exact:true}).fill('Estorno informado fictício');await page.getByLabel('Confirmo que os valores, data e natureza deste ajuste foram informados; não são estimativas.').check();await page.getByRole('button',{name:'Registrar ajuste informado',exact:true}).click();await expect(page.getByTestId('statement-payment-summary')).toContainText('Revisão necessária');
  await page.getByRole('combobox',{name:'Crédito para associar estorno',exact:true}).selectOption({label:'Crédito do ciclo'});await page.getByRole('combobox',{name:'Fatura do estorno',exact:true}).selectOption({label:'2026-10'});await page.getByRole('combobox',{name:'Crédito efetivo para associar estorno',exact:true}).selectOption({label:'Estorno parcial do ciclo · BRL 20,00'});await page.getByLabel('Magnitude do estorno associado em reais',{exact:true}).fill('20,00');await page.getByLabel('Motivo da associação do estorno',{exact:true}).fill('Devolução parcial desta compra');await page.getByLabel('Confirmo que este estorno integral pertence a esta compra e que conferi sua magnitude.').check();
  await page.route('**/api/expenses/*/refunds',async route=>{expect((await route.fetch()).status()).toBe(201);await route.abort('failed');},{times:1});await page.getByRole('button',{name:'Associar estorno à compra',exact:true}).click();await expect(page.getByRole('status').filter({hasText:/fetch|conexão/i})).toBeVisible();await page.getByRole('button',{name:'Associar estorno à compra',exact:true}).click();await expect(page.getByTestId('expense-refund-summary')).toContainText('Custo elegível: BRL 80,00');await expect(page.getByLabel('Total da compra em reais',{exact:true})).toHaveValue('100,00');await expect(page.getByLabel('Notas da compra',{exact:true})).toHaveValue('Correção manual preservada');
  await coverage();await basis(true);await expect(page.getByTestId('statement-payment-summary')).toContainText('Excedente de crédito para revisão');await expect(page.getByTestId('payment-credit-excess')).toContainText('BRL 20,00');await expect(page.getByTestId('payment-source-summary')).toContainText('Disponível do movimento: BRL 0,00');await expect(page.getByTestId('payment-allocations').getByRole('listitem')).toHaveCount(1);
  await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByTestId('expense-refund-summary').screenshot({path:'test-results/card-cycle-refund-mobile.png'});await page.getByRole('heading',{name:'Pagamentos e alocações da fatura',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:'test-results/card-cycle-credit-mobile.png'});await page.setViewportSize({width:1280,height:900});
  await page.getByLabel('Motivo para desassociar Estorno parcial do ciclo',{exact:true}).fill('Correção explícita da associação');await page.getByRole('button',{name:'Desassociar estorno: Estorno parcial do ciclo',exact:true}).click();await expect(page.getByTestId('expense-refund-summary')).toContainText('Custo elegível: BRL 100,00');await page.getByRole('combobox',{name:'Registro para revisar ajuste',exact:true}).selectOption({label:'Estorno parcial do ciclo · BRL 20,00'});await page.getByLabel('Data da reversão informada',{exact:true}).fill('2026-11-10');await page.getByLabel('Descrição da reversão',{exact:true}).fill('Reversão informada do estorno');await page.getByLabel('Valor da reversão com sinal',{exact:true}).fill('-20,00');await page.getByRole('combobox',{name:'Natureza da reversão',exact:true}).selectOption('other_debit');await page.getByLabel('Magnitude da reversão em reais',{exact:true}).fill('20,00');await page.getByLabel('Motivo da reversão',{exact:true}).fill('Instituição corrigiu o estorno fictício');await page.getByLabel('Confirmo a reversão informada, com mesma magnitude e efeito contrário, preservando o original.').check();await page.getByRole('button',{name:'Registrar reversão do ajuste',exact:true}).click();await coverage();await basis();await expect(page.getByTestId('statement-payment-summary')).toContainText('Estado: Pago pelas alocações');await expect(page.getByTestId('installment-plan-summary')).toContainText('2 cobranças conciliadas');
  const bank=(await(await page.request.get('/api/accounts')).json())[0];expect((await(await page.request.get(`/api/entries?kind=bank&accountId=${bank.id}`)).json()).total).toBe(1);await page.getByRole('button',{name:'Histórico de estornos da compra',exact:true}).click();await expect(page.getByRole('heading',{name:'Últimos 20 vínculos de estorno',exact:true})).toBeVisible();await page.getByRole('button',{name:'Histórico de ajustes da fatura',exact:true}).click();await expect(page.getByRole('heading',{name:'Últimos 20 comandos de ajuste',exact:true})).toBeVisible();
});
