import { test, expect } from './fixtures';
import { randomUUID } from 'node:crypto';
import { mailLink } from '../../scripts/test-mail.mjs';

test('create a manual purchase, recover lost response, link a later import and preserve knowledge through edits', async ({ page }) => {
  const origin = 'http://127.0.0.1:15173'; const email = `purchase-${randomUUID()}@rovere.test`; const password = 'Fictitious-browser-123!';
  expect((await page.request.post('/api/auth/sign-up/email', { headers: { Origin: origin }, data: { name: 'Pessoa fictícia', email, password } })).status()).toBe(200);
  await page.goto(await mailLink(email, 'Confirme')); await page.getByLabel('Email', { exact: true }).fill(email); await page.getByLabel('Senha', { exact: true }).fill(password); await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await page.getByLabel('Descrição da compra', { exact: true }).fill('Compra manual fictícia'); await page.getByLabel('Notas da compra', { exact: true }).fill('Minha correção manual');
  await page.route('**/api/expenses', async route => { if (route.request().method() === 'POST') { expect((await route.fetch()).status()).toBe(201); await route.abort('failed'); } else await route.continue(); }, { times: 1 });
  await page.getByRole('button', { name: 'Cadastrar compra', exact: true }).click(); await expect(page.getByRole('status').filter({ hasText: /fetch|conexão/i })).toBeVisible();
  await page.getByRole('button', { name: 'Cadastrar compra', exact: true }).click(); await expect(page.getByTestId('expense-summary')).toContainText('Dados parciais');
  expect((await (await page.request.get('/api/expenses')).json()).total).toBe(1);
  await expect(page.getByTestId('expense-summary')).toContainText('Total da compra: Não informado');
  await page.getByRole('button', { name: 'Abrir compra: Compra manual fictícia', exact: true }).click(); await expect(page.getByLabel('Notas da compra', { exact: true })).toHaveValue('Minha correção manual');
  await page.getByLabel('Nome da conta de crédito').fill('Crédito da compra'); await page.getByRole('button', { name: 'Adicionar conta de crédito', exact: true }).click();
  await page.getByLabel('Competência da fatura').fill('2026-10'); await page.getByRole('button', { name: 'Confirmar competência', exact: true }).click();
  await page.getByRole('combobox', { name: 'Natureza do CSV', exact: true }).selectOption('card');
  await page.getByText('Colunas opcionais', { exact: true }).click(); await page.getByLabel('Identificador externo', { exact: true }).fill('ID'); await page.getByLabel('Número da parcela', { exact: true }).fill('Número'); await page.getByLabel('Quantidade de parcelas', { exact: true }).fill('Quantidade');
  const csv = 'Data;Descrição;Valor;ID;Número;Quantidade\n08/10/2026;Parcela importada 03/10;-120,00;purchase-3-of-10;3;10';
  await page.getByLabel('Arquivo para revisão').setInputFiles({ name: 'purchase.csv', mimeType: 'text/csv', buffer: Buffer.from(csv) }); await page.getByLabel('Conferi o mapeamento, a moeda BRL e os formatos acima.').check(); await page.getByRole('button', { name: 'Enviar para revisão', exact: true }).click();
  await expect(page.getByTestId('import-status')).toContainText('Em revisão'); await page.getByRole('combobox', { name: 'Crédito para este bloco', exact: true }).selectOption({ label: 'Crédito da compra' }); await page.getByRole('combobox', { name: 'Competência para este bloco', exact: true }).selectOption({ label: '2026-10' }); await page.getByRole('button', { name: 'Salvar destino do bloco 1', exact: true }).click();
  await expect(page.getByTestId('confirmation-preview')).toHaveText('1 novos · 0 vinculados · 0 ignorados'); await page.getByRole('button', { name: 'Confirmar registros selecionados', exact: true }).click(); await expect(page.getByTestId('confirmation-result')).toHaveText('1 novos · 0 vinculados · 0 ignorados');
  await page.getByRole('combobox', { name: 'Crédito para associar cobrança', exact: true }).selectOption({ label: 'Crédito da compra' });
  const dropdown = page.getByRole('combobox', { name: 'Cobrança para associar', exact: true }); await expect(dropdown).toBeEnabled(); await dropdown.selectOption({ label: '2026-10-08 · Parcela importada 03/10 · BRL -120,00' });
  await page.getByLabel('Confirmo que a cobrança selecionada pertence a esta compra.').check(); await page.getByRole('button', { name: 'Associar cobrança à compra', exact: true }).click();
  await expect(page.getByTestId('expense-charges')).toContainText('Parcela importada 03/10'); await expect(page.getByTestId('expense-summary')).toContainText('Total da compra: Não informado'); await expect(page.getByLabel('Data original da compra', { exact: true })).toHaveValue('');
  await page.reload(); await page.getByRole('button', { name: 'Abrir compra: Compra manual fictícia', exact: true }).click(); await expect(page.getByTestId('expense-charges')).toContainText('Parcela importada 03/10'); await expect(page.getByLabel('Notas da compra', { exact: true })).toHaveValue('Minha correção manual');
  const purchase = (await (await page.request.get('/api/expenses')).json()).rows[0]; const current = await (await page.request.get(`/api/expenses/${purchase.id}`)).json();
  expect((await page.request.patch(`/api/expenses/${purchase.id}`, { headers: { Origin: origin, 'Idempotency-Key': randomUUID() }, data: { expectedVersion: current.version, notes: 'Correção em outra sessão' } })).status()).toBe(200);
  await page.getByLabel('Total da compra em reais', { exact: true }).fill('100,01'); await page.getByRole('button', { name: 'Salvar compra', exact: true }).click(); await expect(page.getByRole('status').filter({ hasText: 'A compra mudou' })).toBeVisible();
  await page.getByRole('button', { name: 'Recarregar compra e cobranças', exact: true }).click(); await expect(page.getByLabel('Notas da compra', { exact: true })).toHaveValue('Correção em outra sessão');
  await page.getByLabel('Data original da compra', { exact: true }).fill('2026-09-01'); await page.getByLabel('Total da compra em reais', { exact: true }).fill('100,01'); await page.getByRole('button', { name: 'Salvar compra', exact: true }).click();
  await expect(page.getByTestId('expense-summary')).toContainText('Dados completos'); await expect(page.getByTestId('expense-summary')).toContainText('Total da compra: BRL 100,01');
  await page.getByRole('button', { name: 'Desassociar cobrança: Parcela importada 03/10', exact: true }).click(); await expect(page.getByTestId('expense-summary')).toContainText('0 cobranças associadas');
  const credit = (await (await page.request.get('/api/credit-accounts')).json())[0]; expect((await (await page.request.get(`/api/entries?kind=card&accountId=${credit.id}`)).json()).total).toBe(1);
  await page.getByRole('button', { name: 'Consultar histórico da compra', exact: true }).click(); await expect(page.getByRole('heading', { name: 'Histórico da compra — últimas 20 alterações', exact: true })).toBeVisible(); await expect(page.getByText('Versão 0', { exact: false })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); await page.getByRole('heading', { name: 'Compras', exact: true }).scrollIntoViewIfNeeded(); await page.screenshot({ path: 'test-results/expenses-mobile.png' });
  await page.getByLabel('Data original da compra', { exact: true }).scrollIntoViewIfNeeded(); await page.screenshot({ path: 'test-results/expenses-editor-mobile.png' });
});
