import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { mailLink } from '../../scripts/test-mail.mjs';

test('register, verify, login, persist, logout and recover access', async ({ page }) => {
  const email = `browser-${randomUUID()}@rovere.test`;
  const password = 'Fictitious-browser-123!';
  await page.goto('/');
  await page.getByRole('button', { name: 'Criar conta', exact: true }).click();
  await page.getByLabel('Seu nome').fill('Pessoa de teste');
  await page.getByLabel('Email', { exact: true }).fill(email);
  await page.getByLabel('Senha', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Criar conta', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Confira seu email');
  await page.goto(await mailLink(email, 'Confirme'));
  await expect(page.getByRole('status')).toContainText('Email confirmado');
  await page.getByLabel('Email', { exact: true }).fill(email);
  await page.getByLabel('Senha', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Suas contas' })).toBeVisible();
  await page.getByLabel('Nome da conta', { exact: true }).fill('Conta fictícia no navegador');
  await page.getByRole('button', { name: 'Adicionar conta', exact: true }).click();
  await expect(page.getByRole('listitem')).toContainText('Conta fictícia no navegador');
  await page.reload();
  await expect(page.getByRole('listitem')).toContainText('Conta fictícia no navegador');
  await page.getByRole('button', { name: 'Sair', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Entre na sua conta' })).toBeVisible();
  await page.getByRole('button', { name: 'Esqueci minha senha' }).click();
  await page.getByLabel('Email', { exact: true }).fill(email);
  await page.getByRole('button', { name: 'Enviar link' }).click();
  await expect(page.getByRole('status')).toContainText('Se esse email');
  // Recovery must also work when the email opens in an already authenticated browser.
  await page.getByRole('button', { name: 'Voltar para entrar' }).click();
  await page.getByLabel('Email', { exact: true }).fill(email);
  await page.getByLabel('Senha', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page.getByRole('listitem')).toContainText('Conta fictícia no navegador');
  await page.goto(await mailLink(email, 'Redefina'));
  await page.getByLabel('Senha', { exact: true }).fill(`${password}new`);
  await page.getByRole('button', { name: 'Salvar nova senha' }).click();
  await expect(page.getByRole('status')).toContainText('Senha redefinida');
  await page.getByLabel('Email', { exact: true }).fill(email);
  await page.getByLabel('Senha', { exact: true }).fill(`${password}new`);
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page.getByRole('listitem')).toContainText('Conta fictícia no navegador');
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/accounts-mobile.png', fullPage: true });
});
