import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { mailLink } from '../../scripts/test-mail.mjs';

test('upload, paginate, correct, select targets and resume CSV and OFX reviews', async ({ page }) => {
  const email = `imports-${randomUUID()}@rovere.test`; const password = 'Fictitious-browser-123!';
  expect((await page.request.post('/api/auth/sign-up/email', { headers: { Origin: 'http://127.0.0.1:15173' }, data: { name: 'Pessoa fictícia', email, password } })).status()).toBe(200);
  await page.goto(await mailLink(email, 'Confirme'));
  await page.getByLabel('Email', { exact: true }).fill(email); await page.getByLabel('Senha', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await page.getByLabel('Nome da conta', { exact: true }).fill('Banco fictício'); await page.getByRole('button', { name: 'Adicionar conta', exact: true }).click();
  await page.getByLabel('Nome da conta de crédito').fill('Crédito fictício'); await page.getByRole('button', { name: 'Adicionar conta de crédito', exact: true }).click();
  await page.getByLabel('Competência da fatura').fill('2026-10'); await page.getByRole('button', { name: 'Confirmar competência', exact: true }).click();
  const csv = 'Data;Descrição;Valor\n' + Array.from({ length: 500 }, (_, index) => `08/10/2026;Fictício ${index + 1};-12,34`).join('\n');
  await page.getByLabel('Arquivo para revisão').setInputFiles({ name: 'fictitious.csv', mimeType: 'text/csv', buffer: Buffer.from(csv) });
  await page.getByLabel('Conferi o mapeamento, a moeda BRL e os formatos acima.').check();
  await page.getByRole('button', { name: 'Enviar para revisão', exact: true }).click();
  await expect(page.getByTestId('import-status')).toContainText('500 registros');
  await page.getByRole('combobox', { name: 'Conta para este bloco', exact: true }).selectOption({ label: 'Banco fictício' });
  await page.getByRole('button', { name: 'Salvar destino do bloco 1', exact: true }).click();
  await expect(page.getByRole('combobox', { name: 'Conta para este bloco', exact: true })).toHaveValue(/.+/);
  await page.getByRole('button', { name: 'Próxima', exact: true }).click(); await expect(page.getByRole('cell', { name: 'Fictício 26', exact: false }).first()).toBeVisible();
  await page.getByRole('button', { name: 'Anterior', exact: true }).click();
  await page.getByRole('button', { name: 'Corrigir linha 1', exact: true }).click();
  await page.getByLabel('Descrição corrigida').fill('Correção manual no navegador'); await page.getByLabel('Valor corrigido em reais').fill('-12,35');
  await page.getByRole('button', { name: 'Salvar correção', exact: true }).click();
  await expect(page.getByRole('cell', { name: 'Correção manual no navegador', exact: false })).toBeVisible();
  await page.getByLabel('Selecionar linha 2', { exact: true }).uncheck(); await expect(page.getByLabel('Selecionar linha 2', { exact: true })).not.toBeChecked();
  await page.reload(); await page.getByRole('button', { name: 'fictitious.csv — Em revisão', exact: true }).click();
  await expect(page.getByRole('cell', { name: 'Correção manual no navegador', exact: false })).toBeVisible();
  await expect(page.getByLabel('Selecionar linha 2', { exact: true })).not.toBeChecked();
  await expect(page.getByRole('combobox', { name: 'Conta para este bloco', exact: true })).toHaveValue(/.+/);
  await page.getByRole('combobox', { name: 'Formato do arquivo', exact: true }).selectOption('ofx');
  await page.getByLabel('Arquivo para revisão').setInputFiles({ name: 'fictitious.ofx', mimeType: 'application/octet-stream', buffer: await readFile('packages/importers/test/fixtures/card-220.ofx') });
  await page.getByRole('button', { name: 'Enviar para revisão', exact: true }).click();
  await expect(page.getByTestId('import-status')).toContainText('Em revisão');
  await expect(page.locator('table')).toContainText('Falta competência confirmada.');
  await page.getByRole('combobox', { name: 'Crédito para este bloco', exact: true }).selectOption({ label: 'Crédito fictício' });
  await page.getByRole('combobox', { name: 'Competência para este bloco', exact: true }).selectOption({ label: '2026-10' });
  await page.getByRole('button', { name: 'Salvar destino do bloco 1', exact: true }).click();
  await expect(page.locator('table')).not.toContainText('Falta competência confirmada.');
  await page.reload(); await page.getByRole('button', { name: 'fictitious.ofx — Em revisão', exact: true }).click();
  await expect(page.getByRole('combobox', { name: 'Competência para este bloco', exact: true })).toHaveValue(/.+/);
  await expect(page.getByRole('combobox', { name: 'Cartão para este bloco', exact: true })).toHaveValue('');
  await page.setViewportSize({ width: 390, height: 844 }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/import-review-mobile.png', fullPage: true });
  await page.getByRole('heading', { name: 'Importar e revisar', exact: true }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'test-results/import-upload-mobile-viewport.png' });
  await page.getByRole('table').scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'test-results/import-rows-mobile-viewport.png' });
  await page.getByRole('button', { name: 'Remover importação e arquivo', exact: true }).click();
  await expect(page.getByTestId('import-status')).toContainText('Removida');
});
