import { test, expect } from './fixtures';
import { randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { mailLink } from '../../scripts/test-mail.mjs';

test('confirm exact forecasts, recover a lost plan response and reconcile later CSV/OFX without inventing charges', async ({ page }) => {
  const origin = 'http://127.0.0.1:15173'; const email = `plan-${randomUUID()}@rovere.test`; const password = 'Fictitious-browser-123!';
  expect((await page.request.post('/api/auth/sign-up/email', { headers: { Origin: origin }, data: { name: 'Pessoa fictícia', email, password } })).status()).toBe(200);
  await page.goto(await mailLink(email, 'Confirme')); await page.getByLabel('Email', { exact: true }).fill(email); await page.getByLabel('Senha', { exact: true }).fill(password); await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await page.getByLabel('Nome da conta de crédito').fill('Crédito das parcelas'); await page.getByRole('button', { name: 'Adicionar conta de crédito', exact: true }).click();
  for (const period of ['2026-12', '2027-01']) { await page.getByLabel('Competência da fatura').fill(period); await page.getByRole('button', { name: 'Confirmar competência', exact: true }).click(); await expect(page.getByRole('status').filter({ hasText: 'Competência cadastrada e confirmada' })).toBeVisible(); }
  await page.getByLabel('Descrição da compra', { exact: true }).fill('Compra parcelada fictícia'); await page.getByLabel('Total da compra em reais', { exact: true }).fill('100,00'); await page.getByLabel('Notas da compra', { exact: true }).fill('Observação manual'); await page.getByRole('button', { name: 'Cadastrar compra', exact: true }).click();
  await expect(page.getByTestId('expense-summary')).toContainText('Dados parciais');
  await page.getByLabel('Quantidade de parcelas do plano', { exact: true }).fill('3'); await page.getByRole('combobox', { name: 'Crédito do plano', exact: true }).selectOption({ label: 'Crédito das parcelas' }); await page.getByLabel('Primeira competência do plano', { exact: true }).fill('2026-12'); await page.getByLabel('Confirmo o total da compra, a quantidade e o calendário mensal deste plano.').check();
  await page.route('**/api/expenses/*/installment-plan', async route => { expect((await route.fetch()).status()).toBe(201); await route.abort('failed'); }, { times: 1 });
  await page.getByRole('button', { name: 'Confirmar plano de parcelas', exact: true }).click(); await expect(page.getByRole('status').filter({ hasText: /fetch|conexão/i })).toBeVisible(); await page.getByRole('button', { name: 'Confirmar plano de parcelas', exact: true }).click();
  await expect(page.getByTestId('installment-plan-summary')).toContainText('3 previsões pendentes · 0 cobranças conciliadas');
  const table = page.getByRole('table', { name: 'Parcelas previstas e efetivas', exact: true }); await expect(table.getByRole('row').nth(1)).toContainText('33,34'); await expect(table.getByRole('row').nth(3)).toContainText('2027-02');
  const credit = (await (await page.request.get('/api/credit-accounts')).json())[0]; expect((await (await page.request.get(`/api/credit-accounts/${credit.id}/statements`)).json()).length).toBe(2); expect((await (await page.request.get(`/api/entries?kind=card&accountId=${credit.id}`)).json()).total).toBe(0);
  await page.reload(); await page.getByRole('button', { name: 'Abrir compra: Compra parcelada fictícia', exact: true }).click(); await expect(page.getByTestId('installment-plan-summary')).toContainText('3 previsões pendentes');
  await page.getByRole('combobox', { name: 'Natureza do CSV', exact: true }).selectOption('card'); await page.getByText('Colunas opcionais', { exact: true }).click(); await page.getByLabel('Identificador externo', { exact: true }).fill('ID');
  const csv = 'Data;Descrição;Valor;ID\n08/12/2026;Parcela CSV fictícia;-33,35;plan-csv-1';
  const template = await readFile('packages/importers/test/fixtures/card-220.ofx', 'utf8'); const entry = template.match(/<STMTTRN>[\s\S]*?<\/STMTTRN>/)![0].replace(/<FITID>[^<]+<\/FITID>/, '<FITID>plan-ofx-2</FITID>').replace(/<DTPOSTED>[^<]+<\/DTPOSTED>/, '<DTPOSTED>20270108</DTPOSTED>').replace(/<TRNAMT>[^<]+<\/TRNAMT>/, '<TRNAMT>-33.33</TRNAMT>'); const ofx = template.replace(/<STMTTRN>[\s\S]*<\/STMTTRN>/, entry);
  for (const [format, contents, period, ordinal, amount] of [['csv', csv, '2026-12', '1', '33,35'], ['ofx', ofx, '2027-01', '2', '33,33']] as const) {
    await page.getByRole('combobox', { name: 'Formato do arquivo', exact: true }).selectOption(format); if (format === 'csv') await page.getByLabel('Conferi o mapeamento, a moeda BRL e os formatos acima.').check();
    await page.getByLabel('Arquivo para revisão').setInputFiles({ name: `plan.${format}`, mimeType: 'application/octet-stream', buffer: Buffer.from(contents) }); await page.getByRole('button', { name: 'Enviar para revisão', exact: true }).click();
    await expect(page.getByTestId('import-status')).toContainText('Em revisão'); await page.getByRole('combobox', { name: 'Crédito para este bloco', exact: true }).selectOption({ label: 'Crédito das parcelas' }); await page.getByRole('combobox', { name: 'Competência para este bloco', exact: true }).selectOption({ label: period }); await page.getByRole('button', { name: 'Salvar destino do bloco 1', exact: true }).click();
    await expect(page.getByTestId('confirmation-preview')).toHaveText('1 novos · 0 vinculados · 0 ignorados'); await page.getByRole('button', { name: 'Confirmar registros selecionados', exact: true }).click(); await expect(page.getByTestId('confirmation-result')).toHaveText('1 novos · 0 vinculados · 0 ignorados');
    await page.getByRole('combobox', { name: 'Parcela prevista para conciliar', exact: true }).selectOption(ordinal); const selector = page.getByRole('combobox', { name: 'Cobrança para conciliar', exact: true }); await expect(selector).toBeEnabled(); await selector.selectOption({ index: 1 });
    await page.getByLabel('Valor efetivo confirmado em reais', { exact: true }).fill(amount); await page.getByLabel('Confirmo a parcela selecionada, o vínculo com esta compra e o valor efetivo informado.').check(); await page.getByRole('button', { name: 'Conciliar parcela com cobrança', exact: true }).click();
    await expect(page.getByTestId('installment-plan-summary')).toContainText(`${ordinal} cobranças conciliadas`);
  }
  await expect(table.getByRole('row').nth(1)).toContainText('0,01'); await expect(table.getByRole('row').nth(1)).toContainText('Origem: BRL -33,35'); await expect(table.getByRole('row').nth(3)).toContainText('Previsão'); await expect(page.getByLabel('Data original da compra', { exact: true })).toHaveValue(''); await expect(page.getByLabel('Notas da compra', { exact: true })).toHaveValue('Observação manual');
  await page.getByLabel('Total da compra em reais', { exact: true }).fill('100,01'); await page.getByRole('button', { name: 'Salvar compra', exact: true }).click(); await expect(page.getByRole('status').filter({ hasText: 'O total tem um plano confirmado' })).toBeVisible();
  await page.getByRole('button', { name: 'Recarregar compra e cobranças', exact: true }).click(); await expect(page.getByLabel('Total da compra em reais', { exact: true })).toHaveValue('100,00');
  await page.setViewportSize({ width: 390, height: 844 }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); await page.getByRole('heading', { name: 'Plano de parcelas', exact: true }).scrollIntoViewIfNeeded(); await page.screenshot({ path: 'test-results/installment-plans-mobile.png' });
  await page.getByRole('button', { name: 'Desconciliar parcela 1', exact: true }).click(); await expect(page.getByTestId('installment-plan-summary')).toContainText('2 previsões pendentes · 1 cobranças conciliadas');
  expect((await (await page.request.get(`/api/entries?kind=card&accountId=${credit.id}`)).json()).total).toBe(2); await expect(page.getByTestId('expense-charges').getByRole('listitem')).toHaveCount(2);
  await page.getByRole('button', { name: 'Consultar histórico da compra', exact: true }).click(); await expect(page.getByRole('heading', { name: 'Histórico da compra — últimas 20 alterações', exact: true })).toBeVisible(); await expect(page.getByText('Plano: 3 parcelas, 2 conciliadas', { exact: false })).toBeVisible();
});
