import { test, expect } from './fixtures';
import { randomUUID } from 'node:crypto';
import { mailLink } from '../../scripts/test-mail.mjs';

test('allocate one imported outflow to two invoices, recover lost response and reverse without duplicating cash', async ({ page }) => {
  const origin = 'http://127.0.0.1:15173'; const email = `payment-${randomUUID()}@rovere.test`; const password = 'Fictitious-browser-123!';
  expect((await page.request.post('/api/auth/sign-up/email', { headers: { Origin: origin }, data: { name: 'Pessoa fictícia', email, password } })).status()).toBe(200); await page.goto(await mailLink(email, 'Confirme')); await page.getByLabel('Email', { exact: true }).fill(email); await page.getByLabel('Senha', { exact: true }).fill(password); await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await page.getByLabel('Nome da conta', { exact: true }).fill('Banco do pagamento'); await page.getByRole('button', { name: 'Adicionar conta', exact: true }).click(); await page.getByLabel('Nome da conta de crédito').fill('Crédito do pagamento'); await page.getByRole('button', { name: 'Adicionar conta de crédito', exact: true }).click();
  for (const period of ['2026-10','2026-11']) { await page.getByLabel('Competência da fatura').fill(period); await page.getByRole('button', { name: 'Confirmar competência', exact: true }).click(); await expect(page.getByRole('status').filter({ hasText: 'Competência cadastrada e confirmada' })).toBeVisible(); }
  const csv = 'Data;Descrição;Valor;ID\n08/11/2026;Pagamento conjunto fictício;-100,00;payment-source'; await page.getByText('Colunas opcionais', { exact: true }).click(); await page.getByLabel('Identificador externo', { exact: true }).fill('ID'); await page.getByLabel('Arquivo para revisão').setInputFiles({ name: 'payment.csv', mimeType: 'text/csv', buffer: Buffer.from(csv) }); await page.getByLabel('Conferi o mapeamento, a moeda BRL e os formatos acima.').check(); await page.getByRole('button', { name: 'Enviar para revisão', exact: true }).click(); await expect(page.getByTestId('import-status')).toContainText('Em revisão'); await page.getByRole('combobox', { name: 'Conta para este bloco', exact: true }).selectOption({ label: 'Banco do pagamento' }); await page.getByRole('button', { name: 'Salvar destino do bloco 1', exact: true }).click(); await expect(page.getByTestId('confirmation-preview')).toHaveText('1 novos · 0 vinculados · 0 ignorados'); await page.getByRole('button', { name: 'Confirmar registros selecionados', exact: true }).click(); await expect(page.getByTestId('confirmation-result')).toHaveText('1 novos · 0 vinculados · 0 ignorados');
  const summary = page.getByTestId('statement-payment-summary'); const source = page.getByTestId('payment-source-summary');
  async function selectInvoice(period: string, total: string) {
    await page.getByRole('combobox', { name: 'Fatura para editar', exact: true }).selectOption({ label: period }); await page.getByLabel('Total declarado em reais', { exact: true }).fill(total); await page.getByRole('button', { name: 'Salvar dados da fatura', exact: true }).click(); await expect(page.getByTestId('statement-facts-summary')).toContainText(`Total declarado: BRL ${total}`);
    await page.getByRole('combobox', { name: 'Base da obrigação para pagamento', exact: true }).selectOption('declared'); await page.getByLabel('Confirmo que esta base é o total da obrigação antes dos pagamentos, mesmo quando houver divergência.').check(); await page.getByLabel('Confirmo que a base não repete obrigação já representada em outra fatura.').check(); await page.getByRole('button', { name: 'Confirmar base para pagamentos', exact: true }).click(); await expect(summary).toContainText('Estado: Não pago');
    await page.getByRole('combobox', { name: 'Conta bancária do pagamento', exact: true }).selectOption({ label: 'Banco do pagamento' }); await page.getByRole('combobox', { name: 'Movimento bancário para alocar', exact: true }).selectOption({ label: '2026-11-08 · Pagamento conjunto fictício · BRL -100,00' }); await expect(source).toContainText('Data de caixa: 2026-11-08');
  }
  async function fillPayment(amount: string) { await page.getByLabel('Magnitude total da saída em reais', { exact: true }).fill('100,00'); await page.getByLabel('Valor a alocar nesta fatura em reais', { exact: true }).fill(amount); await page.getByLabel('Confirmo que este movimento é uma saída bancária e que os valores informados correspondem ao pagamento desta fatura.').check(); }
  await selectInvoice('2026-10', '60,00'); await fillPayment('30,00'); await page.route('**/api/credit-accounts/*/statements/*/payments', async route => { if (route.request().method() === 'POST') { expect((await route.fetch()).status()).toBe(201); await route.abort('failed'); } else await route.continue(); }, { times: 1 });
  await page.getByRole('button', { name: 'Alocar pagamento bancário', exact: true }).click(); await expect(page.getByRole('status').filter({ hasText: /fetch|conexão/i })).toBeVisible(); await page.getByRole('button', { name: 'Alocar pagamento bancário', exact: true }).click(); await expect(summary).toContainText('Estado: Parcialmente pago'); await expect(summary).toContainText('Saldo conhecido: BRL 30,00'); await expect(source).toContainText('Disponível do movimento: BRL 70,00'); await expect(page.getByTestId('payment-allocations').getByRole('listitem')).toHaveCount(1);
  await fillPayment('30,00'); await page.getByRole('button', { name: 'Alocar pagamento bancário', exact: true }).click(); await expect(summary).toContainText('Estado: Pago pelas alocações'); await expect(source).toContainText('Disponível do movimento: BRL 40,00');
  await selectInvoice('2026-11', '40,00'); await fillPayment('40,01'); await page.getByRole('button', { name: 'Alocar pagamento bancário', exact: true }).click(); await expect(page.getByRole('status').filter({ hasText: 'O valor supera o disponível' })).toBeVisible(); await fillPayment('40,00'); await page.getByRole('button', { name: 'Alocar pagamento bancário', exact: true }).click(); await expect(summary).toContainText('Estado: Pago pelas alocações'); await expect(source).toContainText('Disponível do movimento: BRL 0,00');
  const account = (await (await page.request.get('/api/accounts')).json())[0]; const entries = await (await page.request.get(`/api/entries?kind=bank&accountId=${account.id}`)).json(); expect(entries.total).toBe(1); expect(entries.rows[0].amount.cents).toBe('-10000');
  await page.reload(); await page.getByRole('combobox', { name: 'Conta de crédito', exact: true }).selectOption({ label: 'Crédito do pagamento' }); await page.getByRole('combobox', { name: 'Fatura para editar', exact: true }).selectOption({ label: '2026-11' }); await expect(summary).toContainText('Estado: Pago pelas alocações');
  await page.getByRole('button', { name: 'Reverter alocação de BRL 40,00', exact: true }).click(); await expect(summary).toContainText('Estado: Não pago'); await expect(summary).toContainText('Saldo conhecido: BRL 40,00'); await expect(page.getByTestId('payment-allocations')).toContainText('Revertida');
  await page.getByRole('combobox', { name: 'Conta bancária do pagamento', exact: true }).selectOption({ label: 'Banco do pagamento' }); await page.getByRole('combobox', { name: 'Movimento bancário para alocar', exact: true }).selectOption({ label: '2026-11-08 · Pagamento conjunto fictício · BRL -100,00' }); await expect(source).toContainText('Disponível do movimento: BRL 40,00');
  await page.getByRole('button', { name: 'Consultar histórico de pagamentos', exact: true }).click(); await expect(page.getByRole('heading', { name: 'Últimos 20 comandos de pagamento', exact: true })).toBeVisible(); await expect(page.getByText('Reversão', { exact: false })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); await page.getByRole('heading', { name: 'Pagamentos e alocações da fatura', exact: true }).scrollIntoViewIfNeeded(); await page.screenshot({ path: 'test-results/statement-payments-mobile.png' }); await summary.screenshot({ path: 'test-results/statement-payments-summary-mobile.png' });
});
