import { test, expect } from './fixtures';
import { randomUUID } from 'node:crypto';
import { mailLink } from '../../scripts/test-mail.mjs';

test('classify an imported statement explicitly, confirm coverage, review differences and handle stale edits', async ({ page }) => {
  const origin = 'http://127.0.0.1:15173'; const email = `calculation-${randomUUID()}@rovere.test`; const password = 'Fictitious-browser-123!';
  expect((await page.request.post('/api/auth/sign-up/email', { headers: { Origin: origin }, data: { name: 'Pessoa fictícia', email, password } })).status()).toBe(200);
  await page.goto(await mailLink(email, 'Confirme')); await page.getByLabel('Email', { exact: true }).fill(email); await page.getByLabel('Senha', { exact: true }).fill(password); await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await page.getByLabel('Nome da conta de crédito').fill('Crédito da classificação'); await page.getByRole('button', { name: 'Adicionar conta de crédito', exact: true }).click(); await page.getByLabel('Competência da fatura').fill('2026-10'); await page.getByRole('button', { name: 'Confirmar competência', exact: true }).click();
  await page.getByRole('combobox', { name: 'Fatura para editar', exact: true }).selectOption({ label: '2026-10' }); const summary = page.getByTestId('statement-calculation-summary'); await expect(summary).toContainText('Total calculado completo: Não disponível');
  await page.getByLabel('Total declarado em reais', { exact: true }).fill('95,01'); await page.getByRole('button', { name: 'Salvar dados da fatura', exact: true }).click(); await expect(page.getByTestId('statement-facts-summary')).toContainText('Total declarado: BRL 95,01');
  const csv = 'Data;Descrição;Valor;ID\n08/10/2026;Compra fictícia;-100,00;p\n08/10/2026;Tarifa fictícia;-5,00;f\n08/10/2026;Estorno fictício;10,00;r\n08/10/2026;Pagamento fictício;50,00;t';
  await page.getByRole('combobox', { name: 'Natureza do CSV', exact: true }).selectOption('card'); await page.getByText('Colunas opcionais', { exact: true }).click(); await page.getByLabel('Identificador externo', { exact: true }).fill('ID');
  await page.getByLabel('Arquivo para revisão').setInputFiles({ name: 'nature.csv', mimeType: 'text/csv', buffer: Buffer.from(csv) }); await page.getByLabel('Conferi o mapeamento, a moeda BRL e os formatos acima.').check(); await page.getByRole('button', { name: 'Enviar para revisão', exact: true }).click(); await expect(page.getByTestId('import-status')).toContainText('Em revisão');
  await page.getByRole('combobox', { name: 'Crédito para este bloco', exact: true }).selectOption({ label: 'Crédito da classificação' }); await page.getByRole('combobox', { name: 'Competência para este bloco', exact: true }).selectOption({ label: '2026-10' }); await page.getByRole('button', { name: 'Salvar destino do bloco 1', exact: true }).click(); await expect(page.getByTestId('confirmation-preview')).toHaveText('4 novos · 0 vinculados · 0 ignorados'); await page.getByRole('button', { name: 'Confirmar registros selecionados', exact: true }).click(); await expect(page.getByTestId('confirmation-result')).toHaveText('4 novos · 0 vinculados · 0 ignorados');
  await expect(summary).toContainText('4 registros · 4 sem natureza confirmada'); await expect(page.getByRole('button', { name: 'Confirmar cobertura completa dos registros atuais', exact: true })).toBeDisabled();
  await page.route('**/api/card-charges/*/classification', async route => { expect((await route.fetch()).status()).toBe(200); await route.abort('failed'); }, { times: 1 });
  for (const [description, nature, amount] of [['Compra fictícia', 'purchase', '100,00'], ['Tarifa fictícia', 'fee', '5,00'], ['Estorno fictício', 'refund', '10,00'], ['Pagamento fictício', 'payment', '50,00']] as const) {
    await page.getByRole('button', { name: `Classificar: ${description}`, exact: true }).click(); await page.getByRole('combobox', { name: 'Natureza confirmada da linha', exact: true }).selectOption(nature); await page.getByLabel('Magnitude confirmada em reais', { exact: true }).fill(amount); await page.getByLabel('Confirmo a natureza e o valor informados, preservando os dados originais.').check(); await page.getByRole('button', { name: 'Salvar natureza da linha', exact: true }).click();
    if (nature === 'purchase') { await expect(page.getByRole('status').filter({ hasText: /fetch|conexão/i })).toBeVisible(); await page.getByRole('button', { name: 'Salvar natureza da linha', exact: true }).click(); }
    await expect(page.getByRole('status').filter({ hasText: 'Natureza salva' })).toBeVisible();
  }
  await expect(summary).toContainText('0 sem natureza confirmada'); await expect(summary).toContainText('Subtotal conhecido do ciclo: BRL 95,00'); await expect(summary).toContainText('Consumo bruto informado: BRL 105,00'); await expect(summary).toContainText('Pagamentos informados: BRL 50,00'); await expect(summary).toContainText('Total calculado completo: Não disponível');
  await page.getByLabel('Conferi que todos os registros desta fatura estão presentes e têm natureza confirmada.').check(); await page.getByRole('button', { name: 'Confirmar cobertura completa dos registros atuais', exact: true }).click(); await expect(summary).toContainText('Completa e atual'); await expect(summary).toContainText('Total calculado completo: BRL 95,00'); await expect(summary).toContainText('BRL 0,01 · Divergência para revisão');
  await page.reload(); await page.getByRole('combobox', { name: 'Conta de crédito', exact: true }).selectOption({ label: 'Crédito da classificação' }); await page.getByRole('combobox', { name: 'Fatura para editar', exact: true }).selectOption({ label: '2026-10' }); await expect(summary).toContainText('Completa e atual');
  await page.getByRole('button', { name: 'Classificar: Compra fictícia', exact: true }).click(); const creditId = await page.getByRole('combobox', { name: 'Conta de crédito', exact: true }).inputValue(); const statementId = await page.getByRole('combobox', { name: 'Fatura para editar', exact: true }).inputValue(); const rows = (await (await page.request.get(`/api/entries?kind=card&accountId=${creditId}&statementId=${statementId}`)).json()).rows; const purchase = rows.find((row: any) => row.description === 'Compra fictícia');
  expect((await page.request.patch(`/api/card-charges/${purchase.id}/classification`, { headers: { Origin: origin, 'Idempotency-Key': randomUUID() }, data: { expectedVersion: purchase.version, classification: { nature: 'fee', amount: { currency: 'BRL', cents: '10000' } } } })).status()).toBe(200);
  await page.getByRole('combobox', { name: 'Natureza confirmada da linha', exact: true }).selectOption('fee'); await page.getByLabel('Confirmo a natureza e o valor informados, preservando os dados originais.').check(); await page.getByRole('button', { name: 'Salvar natureza da linha', exact: true }).click(); await expect(page.getByRole('status').filter({ hasText: 'A cobrança mudou' })).toBeVisible();
  await page.getByRole('button', { name: 'Recarregar cobrança para classificar', exact: true }).click(); await expect(page.getByRole('combobox', { name: 'Natureza confirmada da linha', exact: true })).toHaveValue('fee'); await expect(summary).toContainText('Confirmação desatualizada'); await expect(summary).toContainText('Total calculado completo: Não disponível');
  await page.getByLabel('Conferi que todos os registros desta fatura estão presentes e têm natureza confirmada.').check(); await page.getByRole('button', { name: 'Confirmar cobertura completa dos registros atuais', exact: true }).click(); await expect(summary).toContainText('Completa e atual');
  await page.getByRole('button', { name: 'Histórico da natureza da linha', exact: true }).click(); await expect(page.getByRole('heading', { name: 'Últimas 20 classificações', exact: true })).toBeVisible(); await expect(page.getByText('Versão 1', { exact: false })).toBeVisible();
  const original = await (await page.request.get(`/api/card-charges/${purchase.id}`)).json(); expect(original.amount.cents).toBe('-10000'); expect(original.description).toBe('Compra fictícia'); expect((await (await page.request.get(`/api/entries?kind=card&accountId=${creditId}`)).json()).total).toBe(4);
  await page.setViewportSize({ width: 390, height: 844 }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); await page.getByRole('heading', { name: 'Registros e total calculado da fatura', exact: true }).scrollIntoViewIfNeeded(); await page.screenshot({ path: 'test-results/statement-calculation-mobile.png' });
  await summary.screenshot({ path: 'test-results/statement-calculation-totals-mobile.png' });
});
