import { useEffect, useRef, useState } from 'react';
import type { FormEvent } from 'react';
import type { ExpenseDTO } from '@rovere/domain';
import { amountInput, centsInput } from './money-input';
type Api = (path: string, body?: unknown, key?: string, method?: 'GET' | 'POST' | 'PATCH') => Promise<any>;
export function ExpenseRefunds({ value, api, credits, financialVersion, onChanged, parentBusy, setParentBusy }: { value: ExpenseDTO; api: Api; credits: { id: string; name: string }[]; financialVersion: number; onChanged: (value: ExpenseDTO) => void; parentBusy: boolean; setParentBusy: (busy: boolean) => void }) {
  const [creditId, setCreditId] = useState(''); const [statementId, setStatementId] = useState(''); const [statements, setStatements] = useState<{ id: string; period: string }[]>([]); const [rows, setRows] = useState<any[]>([]); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [chargeId, setChargeId] = useState(''); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(''); const [refresh, setRefresh] = useState(0); const [history, setHistory] = useState<any[] | null>(null); const pending = useRef<{ signature: string; key: string; body: unknown } | null>(null);
  useEffect(() => { if (!creditId) return; let active = true; void api(`/credit-accounts/${creditId}/statements`).then(data => { if (active) setStatements(data); }).catch(error => { if (active) setMessage(error.message); }); return () => { active = false; }; }, [creditId, financialVersion]);
  useEffect(() => { if (!statementId) return; let active = true; setLoading(true); setChargeId(''); void api(`/entries?kind=card&accountId=${creditId}&statementId=${statementId}&page=${page}`).then(data => { if (active) { setRows(data.rows); setTotal(data.total); } }).catch(error => { if (active) setMessage(error.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [creditId, statementId, page, refresh, financialVersion, value.version]);
  async function write(charge: any, reason: string, amount?: string) {
    setParentBusy(true); setMessage('');
    try { const target = `/expenses/${value.id}/refunds${amount === undefined ? `/${charge.id}/remove` : ''}`; const signature = JSON.stringify({ target, chargeId: charge.id, expenseVersion: value.version, reason, amount });
      if (pending.current?.signature !== signature) { const statement = await api(`/credit-accounts/${charge.creditAccountId}/statements/${charge.statementId}`); const body = { expectedExpenseVersion: value.version, expectedChargeVersion: charge.version, expectedStatementVersion: statement.version, reason, ...(amount === undefined ? {} : { chargeId: charge.id, amount: { currency: 'BRL', cents: amount }, associationConfirmed: true }) }; pending.current = { signature, key: crypto.randomUUID(), body }; }
      await api(target, pending.current.body, pending.current.key); onChanged(await api(`/expenses/${value.id}`)); pending.current = null; setHistory(null); setRefresh(current => current + 1); setMessage(amount === undefined ? 'Associação removida; crédito e histórico preservados.' : 'Estorno associado; total e plano originais preservados. Revise pagamentos e futuros reembolsos.'); }
    catch (error) { setMessage(error instanceof Error ? error.message : 'Falha de conexão.'); } finally { setParentBusy(false); }
  }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const charge = rows.find(row => row.id === chargeId); if (!charge) return; try { await write({ ...charge, creditAccountId: creditId }, String(data.get('reason') ?? ''), centsInput(String(data.get('amount') ?? ''))); } catch (error) { setMessage(error instanceof Error ? error.message : 'Confira os valores.'); } }
  async function remove(event: FormEvent<HTMLFormElement>, id: string) { event.preventDefault(); const data = new FormData(event.currentTarget); setParentBusy(true); try { const charge = await api(`/card-charges/${id}`); await write(charge, String(data.get('reason') ?? '')); } catch (error) { setMessage(error instanceof Error ? error.message : 'Falha de conexão.'); } finally { setParentBusy(false); } }
  async function showHistory() { setParentBusy(true); try { setHistory(await api(`/expenses/${value.id}/refunds/history`)); } catch (error) { setMessage(error instanceof Error ? error.message : 'Falha de conexão.'); } finally { setParentBusy(false); } }
  const disabled = parentBusy || loading; const refunds = value.refunds;
  return <div className="import-review"><h3>Estornos associados à compra</h3><p>Associe um crédito efetivo confirmado como estorno. Não há redução automática do total original, plano, reembolsos ou caixa.</p>{message && <p role="status">{message}</p>}
    {refunds && <div data-testid="expense-refund-summary"><p>Estornos associados: BRL {amountInput(refunds.refunded.cents)} · Custo elegível: {refunds.eligibleCost.state === 'available' ? `BRL ${amountInput(refunds.eligibleCost.amount.cents)}` : 'Não conhecido'}</p>{refunds.reviewRequired && <p>Confira as relações afetadas; futuros reembolsos/compromissos exigem revisão explícita, sem ajuste silencioso.</p>}</div>}
    <ul>{refunds?.rows.map(row => <li key={row.chargeId}>{row.description} · BRL {amountInput(row.amount.cents)} · {row.reason}<form onSubmit={event => void remove(event, row.chargeId)}><label>Motivo para desassociar {row.description}<input name="reason" required maxLength={1000} disabled={disabled} /></label><button className="secondary" disabled={disabled}>Desassociar estorno: {row.description}</button></form></li>)}</ul>
    <label>Crédito para associar estorno<select value={creditId} disabled={disabled} onChange={event => { setCreditId(event.target.value); setStatements([]); setStatementId(''); setRows([]); setChargeId(''); }}><option value="">Selecione um crédito</option>{credits.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label>
    {creditId && <label>Fatura do estorno<select value={statementId} disabled={disabled} onChange={event => { setStatementId(event.target.value); setPage(1); setRows([]); setChargeId(''); }}><option value="">Selecione uma competência</option>{statements.map(row => <option key={row.id} value={row.id}>{row.period}</option>)}</select></label>}
    {statementId && <><form key={`${value.version}:${statementId}:${refresh}`} onSubmit={save}><label>Crédito efetivo para associar estorno<select required value={chargeId} disabled={disabled} onChange={event => setChargeId(event.target.value)}><option value="">Selecione uma linha classificada como estorno</option>{rows.filter(row => row.classification.state === 'confirmed' && row.classification.value.nature === 'refund').map(row => <option key={row.id} value={row.id}>{row.description} · BRL {amountInput(row.amount.cents)}</option>)}</select></label><label>Magnitude do estorno associado em reais<input name="amount" inputMode="decimal" required disabled={disabled} /></label><label>Motivo da associação do estorno<input name="reason" required maxLength={1000} disabled={disabled} /></label><label className="check"><input type="checkbox" required disabled={disabled} />Confirmo que este estorno integral pertence a esta compra e que conferi sua magnitude.</label><button disabled={disabled || !chargeId}>Associar estorno à compra</button></form><nav><button disabled={disabled || page === 1} className="secondary" onClick={() => setPage(page - 1)}>Estornos anteriores</button><span>Página {page}</span><button disabled={disabled || page * 25 >= total} className="secondary" onClick={() => setPage(page + 1)}>Próximos estornos</button><button disabled={disabled} className="secondary" onClick={() => { pending.current = null; setRefresh(current => current + 1); }}>Atualizar créditos de estorno</button></nav></>}
    <button className="secondary" disabled={disabled} onClick={() => void showHistory()}>Histórico de estornos da compra</button>{history && <div className="statement-history"><h4>Últimos 20 vínculos de estorno</h4>{history.map(row => <p key={row.id}>{row.createdAt} · {row.changes.decision.operation === 'link_refund' ? 'Estorno associado' : 'Estorno desassociado'} · {row.changes.decision.reason}</p>)}</div>}
  </div>;
}
