import { randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { createApp } from '../src/app.js';
import { createDatabase } from '../src/database.js';
import { ImportWorker } from '../src/imports/worker.js';
import { testDatabase } from '../../../scripts/test-database.mjs';
import { mailLink } from '../../../scripts/test-mail.mjs';
const origin = 'http://127.0.0.1:18080'; let database: Awaited<ReturnType<typeof testDatabase>>; let db: ReturnType<typeof createDatabase>; let app: Awaited<ReturnType<typeof createApp>>; let base: string;
let alice: { id: string; cookie: string }; let bob: typeof alice; let credit: { id: string }; let account: { id: string }; let month = 0;
const config = () => ({ databaseUrl: database.url, authSecret: 'test-only-auth-secret-0123456789-abcdefgh', publicOrigin: origin, smtpUrl: process.env.SMTP_URL ?? 'smtp://127.0.0.1:11025', mailFrom: 'noreply@rovere.test', production: false, importsWorkerEnabled: false });
function request(path: string, body?: unknown, method = body === undefined ? 'GET' : 'POST', cookie = alice?.cookie ?? '', extra = {}) { return fetch(`${base}/api${path}`, { method, headers: { Origin: origin, Cookie: cookie, 'Content-Type': 'application/json', 'Idempotency-Key': randomUUID(), ...extra }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }); }
async function register(name: string) { const email = `${name}-${randomUUID()}@rovere.test`; const password = 'Fictitious-adjustment-123!'; const created = await request('/auth/sign-up/email', { name, email, password }); expect(created.status).toBe(200); const user = (await created.json()).user; const link = new URL(await mailLink(email, 'Confirme')); await fetch(`${base}${link.pathname}${link.search}`, { redirect: 'manual' }); const login = await request('/auth/sign-in/email', { email, password }); expect(login.status).toBe(200); return { id: user.id, cookie: login.headers.getSetCookie().map(value => value.split(';')[0]).join('; ') }; }
const money = (cents: string) => ({ currency: 'BRL', cents }); const stmtPath = (id: string) => `/credit-accounts/${credit.id}/statements/${id}`;
async function statement() { const index = month++; return db.statement.create({ data: { userId: alice.id, creditAccountId: credit.id, period: `${2026 + Math.floor(index / 12)}-${String(index % 12 + 1).padStart(2,'0')}`, creationKey: randomUUID() } }); }
async function expense(total: string | null = '10000') { const response = await request('/expenses', { description: 'Compra manual preservada', notes: 'Correção pessoal fictícia', ...(total === null ? {} : { facts: { total: money(total), purchasedOn: '2026-01-01' } }) }); expect(response.status).toBe(201); return response.json(); }
const manualInput = (expectedStatementVersion: number, nature = 'refund', cents = '2000') => ({ expectedStatementVersion, postedOn: '2026-10-08', description: `Ajuste fictício ${nature}`, amount: money(cents), classification: { nature, amount: money(cents) }, reason: 'Informado pela instituição fictícia', informedConfirmed: true });
async function manual(id: string, nature = 'refund', cents = '2000') { const current = await (await request(stmtPath(id))).json(); const response = await request(`${stmtPath(id)}/adjustments`, manualInput(current.version, nature, cents)); expect(response.status).toBe(201); return response.json(); }
async function linkBody(expenseId: string, chargeId: string) { const purchase = await (await request(`/expenses/${expenseId}`)).json(); const charge = await (await request(`/card-charges/${chargeId}`)).json(); const stmt = await (await request(stmtPath(charge.statementId))).json(); return { expectedExpenseVersion: purchase.version, chargeId, expectedChargeVersion: charge.version, expectedStatementVersion: stmt.version, amount: charge.classification.value.amount, reason: 'Estorno desta compra confirmado', associationConfirmed: true }; }
async function link(expenseId: string, chargeId: string) { const response = await request(`/expenses/${expenseId}/refunds`, await linkBody(expenseId, chargeId)); expect(response.status).toBe(201); return response.json(); }
async function remove(expenseId: string, chargeId: string) { const body = await linkBody(expenseId, chargeId); const response = await request(`/expenses/${expenseId}/refunds/${chargeId}/remove`, { expectedExpenseVersion: body.expectedExpenseVersion, expectedChargeVersion: body.expectedChargeVersion, expectedStatementVersion: body.expectedStatementVersion, reason: 'Correção explícita do vínculo' }); expect(response.status).toBe(201); return response.json(); }
async function covered(id: string) { const current = await (await request(stmtPath(id))).json(); expect((await request(stmtPath(id), { expectedVersion: current.version, facts: { coverage: 'complete' } }, 'PATCH')).status).toBe(200); }
async function paymentBasis(id: string, preserve = false) { const state = await (await request(`${stmtPath(id)}/payments`)).json(); const body = { expectedStatementVersion: state.statementVersion, kind: 'calculated', referenceHash: state.candidates.calculated.referenceHash, beforePaymentsConfirmed: true, independentObligationConfirmed: true, ...(preserve ? { preserveOverpaymentConfirmed: true } : {}) }; return request(`${stmtPath(id)}/payments/basis`, body); }
async function importCharge(id: string, text: string, format: 'csv' | 'ofx') { const form = new FormData(); form.append('format', format); form.append('configuration', JSON.stringify(format === 'ofx' ? {} : { profile: { id: 'cycle-fixture', encoding: 'utf-8', delimiter: ';', headerLine: 1, dateFormat: 'YMD', decimal: '.', grouping: null, sign: 'as-is', currency: 'BRL', kind: 'card', columns: { date: 'Date', description: 'Description', amount: 'Amount', externalId: 'ID' } } })); form.append('file', new Blob([text]), `fictitious.${format}`); const uploaded = await fetch(`${base}/api/imports`, { method: 'POST', headers: { Origin: origin, Cookie: alice.cookie, 'Idempotency-Key': randomUUID() }, body: form }); expect(uploaded.status).toBe(201); const batch = await uploaded.json(); await app.get(ImportWorker).runOnce(); const current = await (await request(`/imports/${batch.id}`)).json(); const saved = await (await request(`/imports/${batch.id}/review`, { expectedVersion: current.version, blocks: [{ id: current.blocks[0].id, creditAccountId: credit.id, statementId: id }] }, 'PATCH')).json(); expect((await request(`/imports/${batch.id}/confirm`, { expectedVersion: saved.version })).status).toBe(201); }
beforeAll(async () => { database = await testDatabase(); db = createDatabase(database.url); app = await createApp(config(), db); await app.listen(0,'127.0.0.1'); base = await app.getUrl(); alice = await register('Alice'); bob = await register('Bob'); credit = await (await request('/credit-accounts', { name: 'Crédito fictício' })).json(); account = await (await request('/accounts', { name: 'Banco fictício' })).json(); });
afterAll(async () => { await app?.close(); await database?.close(); });

describe('RF-025 traceable adjustments/refunds and full card cycle', () => {
  it('records informed source idempotently and preserves manual origin and immutable classification', async () => {
    const stmt = await statement(); const body = manualInput(stmt.version); const headers = { 'Idempotency-Key': randomUUID() }; const responses = await Promise.all([request(`${stmtPath(stmt.id)}/adjustments`, body, 'POST', alice.cookie, headers), request(`${stmtPath(stmt.id)}/adjustments`, body, 'POST', alice.cookie, headers)]); expect(responses.map(value => value.status)).toEqual([201,201]); const created = await responses[0]!.json(); expect(await responses[1]!.json()).toEqual(created); expect(created.charge.installment.state).toBe('unknown'); expect(created.charge.amount.cents).toBe('2000');
    const origin = await (await request(`/card-charges/${created.charge.id}`)).json(); expect(origin.manualAdjustment.reason).toBe(body.reason); expect((await request(`/card-charges/${created.charge.id}/classification`, { expectedVersion: 0, classification: null }, 'PATCH')).status).toBe(409); await expect(db.manualCardAdjustment.delete({ where: { chargeId: created.charge.id } })).rejects.toThrow();
    expect((await request(`${stmtPath(stmt.id)}/adjustments`, { ...body, description: 'Different' }, 'POST', alice.cookie, headers)).status).toBe(409);
  });
  it('links full actual refund, preserves total/plan/corrections and caps cumulative eligible cost', async () => {
    const stmt = await statement(); const purchase = await expense(); const plan = await request(`/expenses/${purchase.id}/installment-plan`, { expectedVersion: 0, total: money('10000'), count: 2, creditAccountId: credit.id, firstPeriod: stmt.period, cadence: 'monthly' }); expect(plan.status).toBe(201);
    const a = await manual(stmt.id); const linked = await link(purchase.id, a.charge.id); expect(linked.expense.refunds).toMatchObject({ refunded: { cents: '2000' }, eligibleCost: { amount: { cents: '8000' } }, reviewRequired: true }); expect(linked.expense.facts).toEqual(purchase.facts); expect(linked.expense.notes).toBe(purchase.notes); expect(linked.expense.installmentPlan.forecasts.map((row: any) => row.plannedAmount.cents)).toEqual(['5000','5000']);
    const b = await manual(stmt.id,'refund','9000'); expect((await request(`/expenses/${purchase.id}/refunds`, await linkBody(purchase.id,b.charge.id))).status).toBe(409); expect(await db.expenseRefund.count({ where: { expenseId: purchase.id } })).toBe(1); expect((await db.cardCharge.findUniqueOrThrow({ where: { id: a.charge.id } })).cents).toBe(2000n);
  });
  it('preserves unknown original total and revalidates later confirmation and explicit unlink', async () => {
    const stmt = await statement(); const purchase = await expense(null); const created = await manual(stmt.id); const linked = await link(purchase.id,created.charge.id); expect(linked.expense.refunds.eligibleCost.state).toBe('unknown');
    expect((await request(`/expenses/${purchase.id}`, { expectedVersion: linked.expense.version, facts: { total: money('1000') } }, 'PATCH')).status).toBe(409); const confirmed = await (await request(`/expenses/${purchase.id}`, { expectedVersion: linked.expense.version, facts: { total: money('5000') } }, 'PATCH')).json(); expect(confirmed.refunds.eligibleCost.amount.cents).toBe('3000'); expect((await request(`/expenses/${purchase.id}`, { expectedVersion: confirmed.version, facts: { total: null } }, 'PATCH')).status).toBe(409);
    const removed = await remove(purchase.id,created.charge.id); expect(removed.expense.refunds.refunded.cents).toBe('0'); expect(removed.expense.refunds.eligibleCost.amount.cents).toBe('5000'); expect(await db.cardCharge.findUnique({ where: { id: created.charge.id } })).toBeTruthy();
  });
  it('serializes competing purchases for one credit and replays original link despite later unlink', async () => {
    const stmt = await statement(); const a = await expense(); const b = await expense(); const created = await manual(stmt.id); const bodyA = await linkBody(a.id,created.charge.id); const bodyB = await linkBody(b.id,created.charge.id); const responses = await Promise.all([request(`/expenses/${a.id}/refunds`,bodyA), request(`/expenses/${b.id}/refunds`,bodyB)]); expect(responses.map(row => row.status).sort()).toEqual([201,409]);
    const winner = responses[0]!.status === 201 ? a : b; await remove(winner.id,created.charge.id); const body = await linkBody(winner.id,created.charge.id); const headers = { 'Idempotency-Key': randomUUID() }; const linked = await (await request(`/expenses/${winner.id}/refunds`, body, 'POST',alice.cookie,headers)).json(); await remove(winner.id,created.charge.id); expect(await (await request(`/expenses/${winner.id}/refunds`,body,'POST',alice.cookie,headers)).json()).toEqual(linked);
  });
  it('reverses manual adjustment through one opposite effective row, including another explicit period', async () => {
    const originalStmt = await statement(); const target = await statement(); const original = await manual(originalStmt.id,'fee','500'); const source = await (await request(stmtPath(originalStmt.id))).json(); const body = { ...manualInput(target.version,'other_credit','500'), expectedChargeVersion: original.charge.version, expectedOriginalStatementVersion: source.version }; const headers = { 'Idempotency-Key': randomUUID() };
    const response = await request(`${stmtPath(target.id)}/adjustments/${original.charge.id}/reverse`,body,'POST',alice.cookie,headers); expect(response.status).toBe(201); const reversed = await response.json(); expect(reversed.charge.classification.value.nature).toBe('other_credit'); expect(reversed.charge.statementId).toBe(target.id); expect(await (await request(`${stmtPath(target.id)}/adjustments/${original.charge.id}/reverse`,body,'POST',alice.cookie,headers)).json()).toEqual(reversed);
    const originalRead = await (await request(`/card-charges/${original.charge.id}`)).json(); expect(originalRead.amount.cents).toBe('500'); expect(originalRead.manualAdjustment.reversalChargeId).toBe(reversed.charge.id); expect((await (await request(`/card-charges/${reversed.charge.id}`)).json()).reversalOfChargeId).toBe(original.charge.id);
    const currentTarget = await (await request(stmtPath(target.id))).json(); const currentSource = await (await request(stmtPath(originalStmt.id))).json(); expect((await request(`${stmtPath(target.id)}/adjustments/${original.charge.id}/reverse`, { ...body, expectedStatementVersion: currentTarget.version, expectedChargeVersion: originalRead.version, expectedOriginalStatementVersion: currentSource.version })).status).toBe(409); await expect(db.cardAdjustmentReversal.delete({ where: { originalChargeId: original.charge.id } })).rejects.toThrow();
  });
  it('requires explicit refund unlink before reversal and refuses linking a reversed credit', async () => {
    const stmt = await statement(); const purchase = await expense(); const created = await manual(stmt.id); await link(purchase.id,created.charge.id); const src = await (await request(`/card-charges/${created.charge.id}`)).json(); const current = await (await request(stmtPath(stmt.id))).json(); const body = { ...manualInput(current.version,'other_debit'), expectedChargeVersion: src.version, expectedOriginalStatementVersion: current.version };
    expect((await request(`${stmtPath(stmt.id)}/adjustments/${src.id}/reverse`,body)).status).toBe(409); await remove(purchase.id,src.id); const source = await (await request(`/card-charges/${src.id}`)).json(); const refreshed = await (await request(stmtPath(stmt.id))).json(); expect((await request(`${stmtPath(stmt.id)}/adjustments/${src.id}/reverse`,{ ...body,expectedChargeVersion:source.version,expectedStatementVersion:refreshed.version,expectedOriginalStatementVersion:refreshed.version })).status).toBe(201); expect((await request(`/expenses/${purchase.id}/refunds`,await linkBody(purchase.id,src.id))).status).toBe(409);
  });
  it('rolls back manual creation and dependency changes when journal insertion fails', async () => {
    const stmt = await statement(); const purchase = await expense(); const created = await manual(stmt.id); const body = await linkBody(purchase.id,created.charge.id); const initial = await (await request(`/expenses/${purchase.id}`)).json(); const currentStmt = await (await request(stmtPath(stmt.id))).json(); const count = await db.cardCharge.count();
    await db.$executeRawUnsafe(`CREATE FUNCTION reject_adjustment_command() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Fictitious failure'; END; $$`); await db.$executeRawUnsafe(`CREATE TRIGGER test_adjustment_failure BEFORE INSERT ON "CardAdjustmentCommand" FOR EACH ROW EXECUTE FUNCTION reject_adjustment_command()`);
    try { expect((await request(`${stmtPath(stmt.id)}/adjustments`,manualInput(currentStmt.version,'fee','500'))).status).toBe(500); expect((await request(`/expenses/${purchase.id}/refunds`,body)).status).toBe(500); }
    finally { await db.$executeRawUnsafe('DROP TRIGGER test_adjustment_failure ON "CardAdjustmentCommand"'); await db.$executeRawUnsafe('DROP FUNCTION reject_adjustment_command()'); }
    expect(await db.cardCharge.count()).toBe(count); expect(await (await request(`/expenses/${purchase.id}`)).json()).toEqual(initial); expect(await (await request(stmtPath(stmt.id))).json()).toEqual(currentStmt); expect(await db.expenseRefund.count({ where: { expenseId: purchase.id } })).toBe(0);
  });
  it('isolates APIs/FKs and rejects incompatible input without exposing financial JSON', async () => {
    const stmt = await statement(); const purchase = await expense(); const created = await manual(stmt.id); expect((await request(`/expenses/${purchase.id}/refunds/history`,undefined,'GET',bob.cookie)).status).toBe(404); expect((await request(`${stmtPath(stmt.id)}/adjustments/history`,undefined,'GET',bob.cookie)).status).toBe(404); expect((await request(`/expenses/${purchase.id}/refunds`,await linkBody(purchase.id,created.charge.id),'POST',bob.cookie)).status).toBe(404);
    await expect(db.expenseRefund.create({ data: { chargeId:created.charge.id,creditAccountId:credit.id,userId:bob.id,expenseId:purchase.id,cents:2000n,reason:'Fictitious',evidence:{kind:'user',decisionId:randomUUID()} } })).rejects.toThrow();
    const current = await (await request(stmtPath(stmt.id))).json(); for (const extra of [{ informedConfirmed:false },{ postedOn:'2026-02-30' },{ reason:'' },{ amount:money('1.2') },{ classification:{nature:'purchase',amount:money('2000')} },{ userId:bob.id }]) expect((await request(`${stmtPath(stmt.id)}/adjustments`,{ ...manualInput(current.version),...extra })).status).toBe(400);
    expect((await request(`${stmtPath(stmt.id)}/adjustments`,manualInput(current.version),'POST',alice.cookie,{Origin:'https://attacker.test'})).status).toBe(403); const malformed = await fetch(`${base}/api${stmtPath(stmt.id)}/adjustments`,{method:'POST',headers:{Origin:origin,Cookie:alice.cookie,'Content-Type':'application/json'},body:'{"private":"fictitious-sensitive-value"'}); expect(malformed.status).toBe(400); expect(await malformed.text()).not.toContain('fictitious-sensitive-value');
  });
  it('persists journal and replays commands after restart while preserving immutable snapshots', async () => {
    const stmt = await statement(); const body = manualInput(stmt.version); const headers = {'Idempotency-Key':randomUUID()}; const created = await (await request(`${stmtPath(stmt.id)}/adjustments`,body,'POST',alice.cookie,headers)).json(); const history = await (await request(`${stmtPath(stmt.id)}/adjustments/history`)).json(); await expect(db.cardAdjustmentCommand.update({where:{id:history[0].id},data:{requestHash:'b'.repeat(64)}})).rejects.toThrow(); await app.close(); db=createDatabase(database.url); app=await createApp(config(),db); await app.listen(0,'127.0.0.1'); base=await app.getUrl(); expect(await (await request(`${stmtPath(stmt.id)}/adjustments`,body,'POST',alice.cookie,headers)).json()).toEqual(created);
  });
  it('validates purchase-plan-CSV/OFX-invoices-payment-refund without freeing real paid cash', async () => {
    const a = await statement(); const b = await statement(); const purchase = await expense(); expect((await request(`/expenses/${purchase.id}/installment-plan`,{expectedVersion:0,total:money('10000'),count:2,creditAccountId:credit.id,firstPeriod:a.period,cadence:'monthly'})).status).toBe(201);
    const csvId=randomUUID(),ofxId=randomUUID(); const csv=`Date;Description;Amount;ID\n2026-10-08;Compra CSV fictícia;-50.00;${csvId}`; const template=await readFile('packages/importers/test/fixtures/card-220.ofx','utf8'); const entry=template.match(/<STMTTRN>[\s\S]*?<\/STMTTRN>/)![0].replace(/<FITID>[^<]+<\/FITID>/,`<FITID>${ofxId}</FITID>`).replace(/<TRNAMT>[^<]+<\/TRNAMT>/,'<TRNAMT>-50.00</TRNAMT>'); const ofx=template.replace(/<STMTTRN>[\s\S]*<\/STMTTRN>/,entry); await importCharge(a.id,csv,'csv'); await importCharge(b.id,ofx,'ofx');
    for (const [id,number] of [[csvId,1],[ofxId,2]] as const) { const row=await db.cardCharge.findFirstOrThrow({where:{identities:{some:{externalId:id}}}}); expect((await request(`/card-charges/${row.id}/classification`,{expectedVersion:0,classification:{nature:'purchase',amount:money('5000')}},'PATCH')).status).toBe(200); const exp=await (await request(`/expenses/${purchase.id}`)).json(); expect((await request(`/expenses/${purchase.id}/installment-plan/matches`,{expectedVersion:exp.version,number,chargeId:row.id,confirmedAmount:money('5000')})).status).toBe(201); }
    await covered(a.id); expect((await paymentBasis(a.id)).status).toBe(201); const state=await (await request(`${stmtPath(a.id)}/payments`)).json(); const bank=await db.bankEntry.create({data:{userId:alice.id,accountId:account.id,postedOn:new Date('2026-11-01T00:00:00Z'),description:'Pagamento real fictício',cents:-5000n,fingerprint:'f'.repeat(64)}}); expect((await request(`${stmtPath(a.id)}/payments`,{expectedStatementVersion:state.statementVersion,bankEntryId:bank.id,expectedBankVersion:0,confirmedOutflow:money('5000'),outflowConfirmed:true,amount:money('5000')})).status).toBe(201);
    const refund=await manual(a.id); await link(purchase.id,refund.charge.id); await covered(a.id); expect((await paymentBasis(a.id)).status).toBe(409); const reviewed=await paymentBasis(a.id,true); expect(reviewed.status).toBe(201); const result=await reviewed.json(); expect(result.statement.progress).toMatchObject({state:'credit_review_required',allocated:{cents:'5000'},remaining:{amount:{cents:'0'}},creditExcess:{amount:{cents:'2000'}}});
    const cash=await (await request(`/bank-entries/${bank.id}/payment-source`)).json(); expect(cash.available.amount.cents).toBe('0'); expect(cash.allocated.cents).toBe('5000'); expect(await db.bankEntry.count({where:{id:bank.id}})).toBe(1); const final=await (await request(`/expenses/${purchase.id}`)).json(); expect(final.facts).toEqual(purchase.facts); expect(final.notes).toBe(purchase.notes); expect(final.refunds.eligibleCost.amount.cents).toBe('8000'); expect(final.installmentPlan.forecasts.map((row:any)=>row.plannedAmount.cents)).toEqual(['5000','5000']);
    const before=await db.cardCharge.count(); await importCharge(a.id,csv,'csv'); await importCharge(b.id,ofx,'ofx'); expect(await db.cardCharge.count()).toBe(before); expect((await (await request(`${stmtPath(a.id)}/payments`)).json()).progress).toEqual(result.statement.progress);
  });
});
