import { randomUUID } from 'node:crypto';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { createApp } from '../src/app.js';
import { createDatabase } from '../src/database.js';
import { ImportWorker } from '../src/imports/worker.js';
import { testDatabase } from '../../../scripts/test-database.mjs';
import { mailLink } from '../../../scripts/test-mail.mjs';
const origin = 'http://127.0.0.1:18080'; let database: Awaited<ReturnType<typeof testDatabase>>; let db: ReturnType<typeof createDatabase>; let app: Awaited<ReturnType<typeof createApp>>; let base: string;
let alice: { id: string; cookie: string }; let bob: typeof alice; let credit: { id: string }; let bank: { id: string }; let periodIndex = 0;
const config = () => ({ databaseUrl: database.url, authSecret: 'test-only-auth-secret-0123456789-abcdefgh', publicOrigin: origin, smtpUrl: process.env.SMTP_URL ?? 'smtp://127.0.0.1:11025', mailFrom: 'noreply@rovere.test', production: false, importsWorkerEnabled: false });
function request(path: string, body?: unknown, method = body === undefined ? 'GET' : 'POST', cookie = alice?.cookie ?? '', extra = {}) { return fetch(`${base}/api${path}`, { method, headers: { Origin: origin, Cookie: cookie, 'Content-Type': 'application/json', 'Idempotency-Key': randomUUID(), ...extra }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }); }
async function register(label: string) { const email = `${label}-${randomUUID()}@rovere.test`; const password = 'Fictitious-payments-123!'; const signup = await request('/auth/sign-up/email', { name: label, email, password }); expect(signup.status).toBe(200); const user = (await signup.json()).user; const url = new URL(await mailLink(email, 'Confirme')); await fetch(`${base}${url.pathname}${url.search}`, { redirect: 'manual' }); const login = await request('/auth/sign-in/email', { email, password }); expect(login.status).toBe(200); return { id: user.id, cookie: login.headers.getSetCookie().map(value => value.split(';')[0]).join('; ') }; }
const money = (cents: string) => ({ currency: 'BRL', cents });
const path = (id: string) => `/credit-accounts/${credit.id}/statements/${id}/payments`;
async function statement(cents: string | null = '10000') { const index = periodIndex++; const row = await db.statement.create({ data: { userId: alice.id, creditAccountId: credit.id, period: `${2026 + Math.floor(index / 12)}-${String(index % 12 + 1).padStart(2, '0')}`, creationKey: randomUUID() } }); if (cents !== null) expect((await request(path(row.id).replace('/payments', ''), { expectedVersion: 0, facts: { declaredTotal: money(cents) } }, 'PATCH')).status).toBe(200); return row; }
async function entry(cents = '-10000', owner = alice, account = bank) { return db.bankEntry.create({ data: { userId: owner.id, accountId: account.id, postedOn: new Date('2027-03-01T00:00:00Z'), description: 'Saída bancária fictícia', cents: BigInt(cents), fingerprint: randomUUID().replaceAll('-', '').padEnd(64, '0') } }); }
async function state(id: string) { const response = await request(path(id)); expect(response.status).toBe(200); return response.json(); }
async function source(id: string) { const response = await request(`/bank-entries/${id}/payment-source`); expect(response.status).toBe(200); return response.json(); }
async function basis(id: string, kind = 'declared') { const value = await state(id); const candidate = value.candidates[kind]; const body = { expectedStatementVersion: value.statementVersion, kind, referenceHash: candidate.referenceHash, beforePaymentsConfirmed: true, independentObligationConfirmed: true }; const response = await request(`${path(id)}/basis`, body); expect(response.status).toBe(201); return response.json(); }
async function allocateBody(id: string, bankId: string, cents = '10000') { const value = await state(id); const movement = await source(bankId); const raw = BigInt(movement.amount.cents); return { expectedStatementVersion: value.statementVersion, bankEntryId: bankId, expectedBankVersion: movement.version, confirmedOutflow: money((raw < 0n ? -raw : raw).toString()), outflowConfirmed: true, amount: money(cents) }; }
async function allocate(id: string, bankId: string, cents = '10000') { const response = await request(path(id), await allocateBody(id, bankId, cents)); expect(response.status).toBe(201); return response.json(); }
async function charge(statementId: string, cents: string, nature: string) { const row = await db.cardCharge.create({ data: { userId: alice.id, creditAccountId: credit.id, statementId, postedOn: new Date('2025-12-31T00:00:00Z'), description: 'Linha fictícia', cents: -BigInt(cents), installment: { state: 'unknown' }, fingerprint: randomUUID().replaceAll('-', '').padEnd(64, '0') } }); expect((await request(`/card-charges/${row.id}/classification`, { expectedVersion: 0, classification: { nature, amount: money(cents) } }, 'PATCH')).status).toBe(200); return row; }
async function importBank(text: string, externalId: string) { const form = new FormData(); form.append('format', 'csv'); form.append('configuration', JSON.stringify({ profile: { id: 'payments-fixture', encoding: 'utf-8', delimiter: ';', headerLine: 1, dateFormat: 'YMD', decimal: '.', grouping: null, sign: 'as-is', currency: 'BRL', kind: 'bank', columns: { date: 'Date', description: 'Description', amount: 'Amount', externalId: 'ID' } } })); form.append('file', new Blob([text]), 'fictitious.csv'); const uploaded = await fetch(`${base}/api/imports`, { method: 'POST', headers: { Origin: origin, Cookie: alice.cookie, 'Idempotency-Key': randomUUID() }, body: form }); expect(uploaded.status).toBe(201); const batch = await uploaded.json(); await app.get(ImportWorker).runOnce(); const current = await (await request(`/imports/${batch.id}`)).json(); const saved = await (await request(`/imports/${batch.id}/review`, { expectedVersion: current.version, blocks: [{ id: current.blocks[0].id, financialAccountId: bank.id }] }, 'PATCH')).json(); expect((await request(`/imports/${batch.id}/confirm`, { expectedVersion: saved.version })).status).toBe(201); return db.bankEntry.findFirstOrThrow({ where: { identities: { some: { externalId } } } }); }
beforeAll(async () => { database = await testDatabase(); db = createDatabase(database.url); app = await createApp(config(), db); await app.listen(0, '127.0.0.1'); base = await app.getUrl(); alice = await register('Alice'); bob = await register('Bob'); credit = await (await request('/credit-accounts', { name: 'Crédito fictício' })).json(); bank = await (await request('/accounts', { name: 'Banco fictício' })).json(); });
afterAll(async () => { await app?.close(); await database?.close(); });

describe('RF-024 typed payments and available money against PostgreSQL', () => {
  it('requires known explicit base/outflow and keeps unknown/zero obligations distinct from payments', async () => {
    const unknown = await statement(null); const movement = await entry(); expect((await state(unknown.id)).progress.state).toBe('unknown'); expect((await source(movement.id)).available.state).toBe('unknown'); expect((await request(path(unknown.id), await allocateBody(unknown.id, movement.id))).status).toBe(409);
    const zero = await statement('0'); await basis(zero.id); expect((await state(zero.id)).progress.state).toBe('no_obligation'); expect((await request(path(zero.id), await allocateBody(zero.id, movement.id, '1'))).status).toBe(409); expect(await db.statementPaymentAllocation.count()).toBe(0); expect((await source(movement.id)).confirmedOutflow).toBeNull();
  });
  it('allocates partial/integral amounts exactly, preserving cash date, raw sign and consumption', async () => {
    const stmt = await statement('10001'); await charge(stmt.id, '10001', 'purchase'); await charge(stmt.id, '10001', 'payment'); await basis(stmt.id); const a = await entry('-3334'); const b = await entry('6667'); const before = await db.bankEntry.count();
    const partial = await allocate(stmt.id, a.id, '3334'); expect(partial.statement.progress).toMatchObject({ state: 'partial', remaining: { amount: { cents: '6667' } } }); const full = await allocate(stmt.id, b.id, '6667'); expect(full.statement.progress).toMatchObject({ state: 'paid', remaining: { amount: { cents: '0' } } }); expect(full.statement.allocations.rows.every((row: any) => row.postedOn === '2027-03-01')).toBe(true);
    expect(await db.bankEntry.count()).toBe(before); expect((await db.bankEntry.findUniqueOrThrow({ where: { id: b.id } })).cents).toBe(6667n); const calculation = await (await request(path(stmt.id).replace('/payments', '/summary'))).json(); expect(calculation.consumptionGross.amount.cents).toBe('10001'); expect(calculation.reportedPayments.amount.cents).toBe('10001'); expect(await db.expense.count()).toBe(0);
  });
  it('splits one movement across two statements and refuses reuse above available money', async () => {
    const a = await statement('10000'); const b = await statement('25000'); await basis(a.id); await basis(b.id); const movement = await entry('-30000'); await allocate(a.id, movement.id, '10000'); expect((await source(movement.id)).available.amount.cents).toBe('20000');
    expect((await request(path(b.id), await allocateBody(b.id, movement.id, '20001'))).status).toBe(409); await allocate(b.id, movement.id, '20000'); expect((await source(movement.id)).available.amount.cents).toBe('0'); expect((await state(b.id)).progress.remaining.amount.cents).toBe('5000');
  });
  it('serializes concurrent requests against one source and revalidates remaining funds on retry', async () => {
    const a = await statement('10000'); const b = await statement('10000'); await basis(a.id); await basis(b.id); const movement = await entry('-10000'); const bodies = await Promise.all([allocateBody(a.id, movement.id, '6000'), allocateBody(b.id, movement.id, '6000')]);
    const responses = await Promise.all([request(path(a.id), bodies[0]), request(path(b.id), bodies[1])]); expect(responses.map(row => row.status).sort()).toEqual([201,409]); const loser = responses[0]!.status === 409 ? a : b; expect((await request(path(loser.id), await allocateBody(loser.id, movement.id, '6000'))).status).toBe(409); expect((await source(movement.id)).allocated.cents).toBe('6000');
  });
  it('serializes two movements against one obligation and rejects overpayment with fresh versions', async () => {
    const stmt = await statement(); await basis(stmt.id); const a = await entry('-6000'); const b = await entry('-6000'); const bodies = await Promise.all([allocateBody(stmt.id, a.id, '6000'), allocateBody(stmt.id, b.id, '6000')]); const responses = await Promise.all([request(path(stmt.id), bodies[0]), request(path(stmt.id), bodies[1])]); expect(responses.map(row => row.status).sort()).toEqual([201,409]); const loser = responses[0]!.status === 409 ? a : b; expect((await request(path(stmt.id), await allocateBody(stmt.id, loser.id, '6000'))).status).toBe(409); expect((await state(stmt.id)).progress.allocated.cents).toBe('6000'); expect((await source(loser.id)).confirmedOutflow).toBeNull();
  });
  it('replays allocation responses after lost replies/later writes and conflicts on changed payload', async () => {
    const stmt = await statement(); await basis(stmt.id); const movement = await entry(); const body = await allocateBody(stmt.id, movement.id, '3000'); const headers = { 'Idempotency-Key': randomUUID() }; const responses = await Promise.all([request(path(stmt.id), body, 'POST', alice.cookie, headers), request(path(stmt.id), body, 'POST', alice.cookie, headers)]); expect(responses.map(row => row.status)).toEqual([201,201]); const original = await responses[0]!.json(); expect(await responses[1]!.json()).toEqual(original); await allocate(stmt.id, movement.id, '1000'); expect(await (await request(path(stmt.id), body, 'POST', alice.cookie, headers)).json()).toEqual(original); expect((await request(path(stmt.id), { ...body, amount: money('3001') }, 'POST', alice.cookie, headers)).status).toBe(409); expect((await state(stmt.id)).progress.allocated.cents).toBe('4000');
  });
  it('flags financial changes for review, preserves allocations and refuses basis below already allocated', async () => {
    const stmt = await statement(); await basis(stmt.id); const movement = await entry(); const allocated = await allocate(stmt.id, movement.id, '6000'); expect((await request(path(stmt.id).replace('/payments',''), { expectedVersion: allocated.statement.statementVersion, facts: { declaredTotal: money('5000') } }, 'PATCH')).status).toBe(200);
    const stale = await state(stmt.id); expect(stale.progress).toMatchObject({ state: 'review_required', allocated: { cents: '6000' }, remaining: { state: 'unknown' } }); expect((await request(path(stmt.id), await allocateBody(stmt.id, movement.id, '1000'))).status).toBe(409);
    const candidate = stale.candidates.declared; expect((await request(`${path(stmt.id)}/basis`, { expectedStatementVersion: stale.statementVersion, kind: 'declared', referenceHash: candidate.referenceHash, beforePaymentsConfirmed: true, independentObligationConfirmed: true })).status).toBe(409);
    const row = stale.allocations.rows[0]; const src = await source(movement.id); expect((await request(`${path(stmt.id)}/${row.id}/reverse`, { expectedStatementVersion: stale.statementVersion, expectedBankVersion: src.version })).status).toBe(201); await basis(stmt.id); expect((await state(stmt.id)).progress.remaining.amount.cents).toBe('5000'); expect((await source(movement.id)).available.amount.cents).toBe('10000');
  });
  it('requires current calculated coverage and blocks identified carried obligations', async () => {
    const stmt = await statement('9900'); await charge(stmt.id, '10000', 'purchase'); let current = await (await request(path(stmt.id).replace('/payments',''))).json(); expect((await request(path(stmt.id).replace('/payments',''), { expectedVersion: current.version, facts: { coverage: 'complete' } }, 'PATCH')).status).toBe(200); await basis(stmt.id, 'calculated'); expect((await state(stmt.id)).basis.total.cents).toBe('10000');
    await charge(stmt.id, '100', 'fee'); expect((await state(stmt.id)).progress.state).toBe('review_required'); const carried = await statement(); await charge(carried.id, '100', 'previous_balance'); expect((await state(carried.id)).blockers).toContain('PREVIOUS_BALANCE_REVIEW_REQUIRED'); expect((await state(carried.id)).candidates.declared).toBeNull();
  });
  it('reverses explicitly without deleting movement/history, preserving immutable values and restarting safely', async () => {
    const stmt = await statement(); await basis(stmt.id); const movement = await entry(); const created = await allocate(stmt.id, movement.id); const allocation = created.statement.allocations.rows[0]; const body = { expectedStatementVersion: created.statement.statementVersion, expectedBankVersion: created.bankEntry.version }; const headers = { 'Idempotency-Key': randomUUID() }; const response = await request(`${path(stmt.id)}/${allocation.id}/reverse`, body, 'POST', alice.cookie, headers); const reversed = await response.json(); expect(reversed.statement.progress.state).toBe('unpaid'); expect(reversed.bankEntry.available.amount.cents).toBe('10000'); expect(reversed.statement.allocations.rows[0].reversedAt).toBeTruthy();
    await expect(db.statementPaymentAllocation.delete({ where: { id: allocation.id } })).rejects.toThrow(); await expect(db.statementPaymentAllocation.update({ where: { id: allocation.id }, data: { cents: 1n } })).rejects.toThrow(); const command = await db.statementPaymentCommand.findFirstOrThrow({ where: { statementId: stmt.id } }); await expect(db.statementPaymentCommand.update({ where: { id: command.id }, data: { requestHash: 'b'.repeat(64) } })).rejects.toThrow();
    await app.close(); db = createDatabase(database.url); app = await createApp(config(), db); await app.listen(0, '127.0.0.1'); base = await app.getUrl(); expect(await (await request(`${path(stmt.id)}/${allocation.id}/reverse`, body, 'POST', alice.cookie, headers)).json()).toEqual(reversed); expect((await request(`${path(stmt.id)}/${allocation.id}/reverse`, { expectedStatementVersion: reversed.statement.statementVersion, expectedBankVersion: reversed.bankEntry.version })).status).toBe(409);
  });
  it('rolls back source/basis/allocation/versions when the immutable command cannot be recorded', async () => {
    const stmt = await statement(); const movement = await entry(); const before = await state(stmt.id); await db.$executeRawUnsafe(`CREATE FUNCTION reject_payment_command() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Fictitious failure'; END; $$`); await db.$executeRawUnsafe(`CREATE TRIGGER test_payment_failure BEFORE INSERT ON "StatementPaymentCommand" FOR EACH ROW EXECUTE FUNCTION reject_payment_command()`);
    try { const candidate = before.candidates.declared; expect((await request(`${path(stmt.id)}/basis`, { expectedStatementVersion: before.statementVersion, kind: 'declared', referenceHash: candidate.referenceHash, beforePaymentsConfirmed: true, independentObligationConfirmed: true })).status).toBe(500); } finally { await db.$executeRawUnsafe('DROP TRIGGER test_payment_failure ON "StatementPaymentCommand"'); }
    expect(await state(stmt.id)).toEqual(before); await basis(stmt.id); const confirmed = await state(stmt.id); await db.$executeRawUnsafe(`CREATE TRIGGER test_payment_failure BEFORE INSERT ON "StatementPaymentCommand" FOR EACH ROW EXECUTE FUNCTION reject_payment_command()`);
    try { expect((await request(path(stmt.id), await allocateBody(stmt.id, movement.id))).status).toBe(500); } finally { await db.$executeRawUnsafe('DROP TRIGGER test_payment_failure ON "StatementPaymentCommand"'); await db.$executeRawUnsafe('DROP FUNCTION reject_payment_command()'); }
    expect(await state(stmt.id)).toEqual(confirmed); expect((await source(movement.id)).version).toBe(0); expect((await source(movement.id)).confirmedOutflow).toBeNull(); expect(await db.statementPaymentAllocation.count({ where: { statementId: stmt.id } })).toBe(0);
  });
  it('isolates endpoints and typed SQL references and rejects invalid values/keys/origins', async () => {
    const stmt = await statement(); await basis(stmt.id); const movement = await entry(); expect((await request(path(stmt.id), undefined, 'GET', bob.cookie)).status).toBe(404); expect((await request(`${path(stmt.id)}/history`, undefined, 'GET', bob.cookie)).status).toBe(404); expect((await request(`/bank-entries/${movement.id}/payment-source`, undefined, 'GET', bob.cookie)).status).toBe(404);
    const otherBank = await (await request('/accounts', { name: 'Banco Bob' }, 'POST', bob.cookie)).json(); const foreign = await entry('-10000', bob, otherBank); expect((await request(path(stmt.id), { ...(await allocateBody(stmt.id, movement.id)), bankEntryId: foreign.id })).status).toBe(404);
    for (const amount of [money('0'), money('-1'), money('1.2'), { currency: 'USD', cents: '1' }]) expect((await request(path(stmt.id), { ...(await allocateBody(stmt.id, movement.id)), amount })).status).toBe(400);
    const body = await allocateBody(stmt.id, movement.id); expect((await request(path(stmt.id), { ...body, outflowConfirmed: false })).status).toBe(400); expect((await request(path(stmt.id), { ...body, confirmedOutflow: money('9999') })).status).toBe(400); expect((await request(path(stmt.id), body, 'POST', alice.cookie, { 'Idempotency-Key': '' })).status).toBe(400); expect((await request(path(stmt.id), body, 'POST', alice.cookie, { Origin: 'https://attacker.test' })).status).toBe(403);
    await expect(db.statementPaymentSource.create({ data: { bankEntryId: movement.id, accountId: bank.id, userId: bob.id, originalCents: -10000n, confirmedCents: 10000n, evidence: { kind: 'user', decisionId: randomUUID() } } })).rejects.toThrow(); expect((await request(path(stmt.id), undefined, 'GET', '')).status).toBe(401);
  });
  it('preserves allocation/source identity on bank reimport', async () => {
    const stmt = await statement(); await basis(stmt.id); const externalId = randomUUID(); const csv = `Date;Description;Amount;ID\n2027-03-01;Pagamento fictício;-100.00;${externalId}`; const movement = await importBank(csv, externalId); await allocate(stmt.id, movement.id); const before = await state(stmt.id); const count = await db.bankEntry.count(); await importBank(csv, externalId); expect(await db.bankEntry.count()).toBe(count); expect(await state(stmt.id)).toEqual(before); expect((await source(movement.id)).available.amount.cents).toBe('0'); expect((await request(`${path(stmt.id)}?page=0`)).status).toBe(400); expect((await (await request(`${path(stmt.id)}/history`)).json()).length).toBe(2);
  });
  it('marks altered source amounts for review and permits reversal without inventing available money', async () => {
    const stmt = await statement(); await basis(stmt.id); const movement = await entry(); const created = await allocate(stmt.id, movement.id, '3000'); const allocation = created.statement.allocations.rows[0];
    await db.bankEntry.update({ where: { id: movement.id }, data: { cents: -5000n } }); expect((await source(movement.id)).available.state).toBe('unknown'); const changed = await state(stmt.id); expect(changed.progress.state).toBe('review_required'); expect(changed.progress.remaining.state).toBe('unknown');
    expect((await request(path(stmt.id), await allocateBody(stmt.id, movement.id, '1000'))).status).toBe(409); expect((await request(`${path(stmt.id)}/${allocation.id}/reverse`, { expectedStatementVersion: changed.statementVersion, expectedBankVersion: created.bankEntry.version })).status).toBe(201); expect((await state(stmt.id)).progress.state).toBe('unpaid'); expect((await source(movement.id)).available.state).toBe('unknown');
  });
  it('paginates actual allocations while all active reservations remain in totals and history is bounded', async () => {
    const stmt = await statement('2600'); await basis(stmt.id); const movement = await entry('-2600'); for (let index = 0; index < 26; index++) await allocate(stmt.id, movement.id, '100');
    const first = await state(stmt.id); const second = await (await request(`${path(stmt.id)}?page=2`)).json(); expect(first.allocations.total).toBe(26); expect(first.allocations.rows).toHaveLength(25); expect(second.allocations.rows).toHaveLength(1); expect(new Set([...first.allocations.rows, ...second.allocations.rows].map((row: any) => row.id)).size).toBe(26); expect(second.progress).toEqual(first.progress); expect(first.progress.allocated.cents).toBe('2600'); expect(first.progress.state).toBe('paid'); expect((await source(movement.id)).available.amount.cents).toBe('0'); expect((await (await request(`${path(stmt.id)}/history`)).json())).toHaveLength(20);
  });
});
